### PR TITLE
Don't send a transaction if a node already has it

### LINKED ISSUE #210: Network manager sends a transaction even if a node already has the transaction
The node implements a `hasTransactionHash` API, but the network manager gossips the transaction to a node even if that node already contains the transaction. 

The node should instead query the target node's `hasTransactionHash()`, and only send the transaction if `hasTransactionHash()` returns false.

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
Logging confirms it works. Devising a specialized test-case just for this functionality is likely not possible.

Fixes #210

### CODE REVIEW

**Comment by Geod24** [comment]
Interestingly, all Mac builds failed

**Comment by AndrejMitrovic** [comment]
Rebased.

**Review by Geod24 — APPROVED** [review]
Random idea: We cache this using bloom filters in the future.

**Comment by AndrejMitrovic** [comment]
> Random idea: We cache this using bloom filters in the future.

Can you elaborate?

**Comment by Geod24** [comment]
Originally I was thinking we would end up calling a node more than once to know if they have a transactions, but realized we would just reject a tx we already have, so it's not a problem.

**Pull request merged**
