### PR TITLE
Integrate Flash into FullNode / Validator and provide FlashThinNode

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
I've considered multiple approaches. But it's not easy due to D not supporting multiple-inheritance. So everything has to be done through interfaces or aggregation.

This is just one approach, maybe you can think of other ideas @omerfirmak?

I tried to add system integration tests, but that test-suite seems to be failing even in v0.x.x (https://github.com/bpfkorea/agora/pull/1718). So I'm blocked on that.

The next step would have been to deploy some flash nodes to our private testnet and have them create channels with each other and send some microtransactions. It's not obvious how this can be done since the nodes have a controller interface but it's not exposed remotely (should only be done locally like the Admin interface thingy).

Anyway this is all WIP.

Part of #1717

### CODE REVIEW

**Comment by omerfirmak** [comment]
I went over it and I think it is a solid start. We should probably merge this and see if we will come across any limitations as we go.

**Comment by AndrejMitrovic** [comment]
I have improvements I'll push soon. Also getting rid of duplicate interfaces. And I just had the first successful vibe.d networking Flash test!

**Comment by AndrejMitrovic** [comment]
I've split it up into multiple commits and I've added a `testing` mode. This is the best I could come up with given the limited time we have.

I've tested this locally with this diff: https://gist.github.com/AndrejMitrovic/12e907f433020bff5321e266b5b8b565

It works quite nicely. Alice pays Charlie's invoice through an intermediate channel. So Flash is confirmed working on TCP/IP.

The testing steps are hardcoded in the classes but we can fix this later.

**Review by omerfirmak — APPROVED** [review]
Great work!

**Comment by AndrejMitrovic** [comment]
> Great work!

Aww thanks buddy!

**Pull request merged**
