### PR TITLE
[CI] Enable verbose dub output for preGenerateCommands

### PR DESCRIPTION
**Pull request by omerfirmak**
Will try to recreate #864

### CODE REVIEW

**Comment by Geod24** [comment]
You could probably modify the Github workflow to just run `dub build`. Even do it in loops until it fails.

**Comment by omerfirmak** [comment]
I couldn't reproduce the issue. @Geod24, Should we merge this and wait for the next time we see it in the wild?

**Comment by Geod24** [comment]
I think that it's a race condition, and so using verbose (and writing to stdout) is enough to delay things enough for it not to happen. Can you reproduce without verbose output ?

**Comment by omerfirmak** [comment]
> Can you reproduce without verbose output ?

Sadly, no.

**Review by Geod24 — APPROVED** [review]
Can't hurt

**Pull request merged**
