### PR TITLE
Fix #2155: Clear registry after nodes are shutdown

### LINKED ISSUE #2155: Race condition in unittest node initialization
Some builds have started to time out with the following error:
```
Unittesting agora.test.QuorumShuffle================================ ASSERT HANDLER ===============================
[source/agora/test/Base.d:1230] Assertion thrown during test: Trying to access node at address 'Validator #4 (boa1xrval5rzmma29zh4aqgv3mvcarhwa0w8rgthy3l9vaj3fywf9894ycmjkm8)' without first creating it
source/agora/test/Base.d:1230 agora.test.Base.TestAPI agora.test.Base.TestNetworkManager.getClient(immutable(char)[], core.time.Duration) [0x1008167c8]
source/agora/network/Manager.d:164 void agora.network.Manager.NetworkManager.ConnectionTask.connect_canthrow() [0x10096fdf8]
source/agora/network/Manager.d:155 nothrow void agora.network.Manager.NetworkManager.ConnectionTask.connect() [0x10096fceb]
core/thread/context.d:46 void core.thread.context.Callable.opCall() [0x101861cee]
core/thread/fiber.d:1129 void core.thread.fiber.Fiber.run() [0x101861e7d]
core/thread/fiber.d:186 fiber_entryPoint [0x101861db2]
#### FATAL ERROR: Trying to access node at address 'Validator #4 (boa1xrval5rzmma29zh4aqgv3mvcarhwa0w8rgthy3l9vaj3fywf9894ycmjkm8)' without first creating it
This node was started at source/agora/test/QuorumShuffle.d:38
This most likely means that the node crashed due to an uncaught exception
If not, please file a bug at https://github.com/Geod24/localrest/
Full error: core.exception.AssertError@source/agora/test/Base.d(1230): Trying to access node at address 'Validator #4 (boa1xrval5rzmma29zh4aqgv3mvcarhwa0w8rgthy3l9vaj3fywf9894ycmjkm8)' without first creating it
----------------
source/agora/test/Base.d:162 nothrow void agora.test.Base.testAssertHandler(immutable(char)[], ulong, immutable(char)[]) [0x10080fd3f]
core/exception.d:448 onAssertErrorMsg [0x101835861]
core/exception.d:590 _d_assert_msg [0x101835c75]
source/agora/test/Base.d:1230 agora.test.Base.TestAPI agora.test.Base.TestNetworkManager.getClient(immutable(char)[], core.time.Duration) [0x1008167c8]
source/agora/network/Manager.d:164 void agora.network.Manager.NetworkManager.ConnectionTask.connect_canthrow() [0x10096fdf8]
source/agora/network/Manager.d:155 nothrow void agora.network.Manager.NetworkManager.ConnectionTask.connect() [0x10096fceb]
core/thread/context.d:46 void core.thread.context.Callable.opCall() [0x101861cee]
core/thread/fiber.d:1129 void core.thread.fiber.Fiber.run() [0x101861e7d]
core/thread/fiber.d:186 fiber_entryPoint [0x101861db2]
================================ ASSERT HANDLER ===============================
[source/agora/test/Base.d:1230] Assertion thrown during test: Trying to access node at address 'Validator #5 (boa1xzval4nvru2ej9m0rptq7hatukkavemryvct4f8smyy3ky9ct5u0s8w6gfy)' without first creating it
source/agora/test/Base.d:1230 agora.test.Base.TestAPI agora.test.Base.TestNetworkManager.getClient(immutable(char)[], core.time.Duration) [0x1008167c8]
source/agora/network/Manager.d:164 void agora.network.Manager.NetworkManager.ConnectionTask.connect_canthrow() [0x10096fdf8]
source/agora/network/Manager.d:155 nothrow void agora.network.Manager.NetworkManager.ConnectionTask.connect() [0x10096fceb]
core/thread/context.d:46 void core.thread.context.Callable.opCall() [0x101861cee]
core/thread/fiber.d:1129 void core.thread.fiber.Fiber.run() [0x101861e7d]
core/thread/fiber.d:186 fiber_entryPoint [0x101861db2]
```

This actually triggers from different tests, not always the same, so it's a general problem.
I'm fairly certain it was introduced by https://github.com/bosagora/agora/commit/df8b09ad89b4c60ec536200c6777feff71484c6a, but I can't figure out why, since the registry (Localrest) is filled in `makeTestNetwork`, and `start` (which calls this) is called from the test itself, after `makeTestNetwork` returns.

### PR DESCRIPTION
**Pull request by omerfirmak**
Closes #2155

### CODE REVIEW

**Review by Geod24 — APPROVED** [review]
Oh damn... Should we also alter the error message, as it can be misleading right now ?

**Comment by omerfirmak** [comment]
> 
> 
> Oh damn... Should we also alter the error message, as it can be misleading right now ?

which error message?

`Trying to access node at address 'Validator #4 (boa1xrval5rzmma29zh4aqgv3mvcarhwa0w8rgthy3l9vaj3fywf9894ycmjkm8)' without first creating it`

this one still makes sense to me

**Comment by Geod24** [comment]
The "first" part could be misleading, since in this case, it was created, but unregistered too early, right ?

**Comment by omerfirmak** [comment]
> The "first" part could be misleading, since in this case, it was created, but unregistered too early, right ?

Yeah, but it actually makes more sense after the fix:) Because registry entries now persist for the whole lifetime of nodes.

**Pull request merged**
