### PR TITLE
Update vanity/system tests dub.json to new submodules

### PR DESCRIPTION
**Pull request by Geod24**
We're not using memutils not its botan-math dependency anymore,
so just remove them so they don't get pulled.
Additionally, the dub.json of vanity was changed
not to reference path, so it can be overridden.

### CODE REVIEW

**Comment by kchulj** [comment]
Relates [faucet#30](https://github.com/bpfkorea/faucet/issues/30).
The submodules and `dub.json` there also need to be updated in order to build with Docker Hub.

**Comment by Geod24** [comment]
I'm not sure I follow your comment. We don't build with docker hub anymore. And is there something else needed on Agora side ?

**Comment by kchulj** [comment]
> I'm not sure I follow your comment. We don't build with docker hub anymore. And is there something else needed on Agora side ?

That was wrong, it is the GitHub Action. I meant, that it would be nice to have the same submodules on faucet as in agora.

**Comment by Geod24** [comment]
@kchulj : So is this PR okay ?

**Review by kchulj — APPROVED** [review]
Yes LGTM.

**Pull request merged**
