### PR TITLE
Fix GitHub CI for windows

### PR DESCRIPTION
**Pull request by TrustHenry**

### CODE REVIEW

**Comment by TrustHenry** [comment]
@hewison-chris Let's see if this works.

**Comment by hewison-chris** [comment]
Maybe this PR is better as it keeps it similar to how we do the linux and Mac jobs. Also the path is known in this step.

**Review by hewison-chris — APPROVED** [review]
Good find

**Comment by TrustHenry** [comment]
@hewison-chris  has a better idea. https://github.com/bpfkorea/agora/pull/1373

**Pull request closed without merging**
