### PR TITLE
Flash: Fix two-way payments

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
This builds on top of the work in https://github.com/bpfkorea/agora/pull/1630

### CODE REVIEW

**Comment by omerfirmak** [comment]
I think we should put an upper bound to the `while(1)` retry loops. That may simplify the process

**Comment by AndrejMitrovic** [comment]
I think another issue is that a payment from A->B can be started at the same time as an update from B->A. I think maybe the solution is to avoid spawning fibers everywhere, and to order the events by weight. Updates would be preferred over payments as this unlocks HTLCs rather than makes new ones.

**Comment by AndrejMitrovic** [comment]
The last commit fixes the first unittest failing. I still think there might be issues with timing though.

**Comment by AndrejMitrovic** [comment]
Ah there is a small bug in that commit too. I'll fix it.

**Comment by AndrejMitrovic** [comment]
I've fixed that last commit again.

**Comment by AndrejMitrovic** [comment]
What can we do about the CI not showing any logs until the tests are done? I can't get the raw logs until done either. So I have no idea where the CI is getting stuck.

**Comment by omerfirmak** [comment]
> What can we do about the CI not showing any logs until the tests are done? I can't get the raw logs until done either. So I have no idea where the CI is getting stuck.

AFAIK, it should show them if you keep the page open from the start.

**Comment by AndrejMitrovic** [comment]
> AFAIK, it should show them if you keep the page open from the start.

I know about this trick but it still fails to show the logs sometimes.

**Comment by AndrejMitrovic** [comment]
All except one have finished green. I wonder if it's the GC thread getting stuck again..

@omerfirmak feel free to merge if you approve.

**Comment by AndrejMitrovic** [comment]
I just realized I should have folded some of these commits. Well, let me know if I should do it.

**Review by omerfirmak — APPROVED** [review]

**Pull request merged**
