### PR TITLE
DNS registry: Various fixes to make TCP actually listen and work

### PR DESCRIPTION
**Pull request by Geod24**
Among a few minor mistakes (e.g. 3rd and 5th commits), and improvements (1st, 2nd, 6th commits) are bug fixes (4th and 7th) which allow messages sent over TCP to be properly parsed, paving the way for AXFR (#2451 ).

### CODE REVIEW

**Comment by kchulj** [comment]
Is the 1st commit planning to be removed from #2487 ? (it seems to fit more here)

**Comment by Geod24** [comment]
Whichever gets merged first gets the crown. It's not needed for either PR, but since I've been hammering at the registry for a while, I have a bunch of small improvements like this.

**Comment by Geod24** [comment]
Rebased

**Review by kchulj — APPROVED** [review]
🆗

**Pull request merged**
