### PR TITLE
Remove agora's Hash module, use our dependency's

### PR DESCRIPTION
**Pull request by Geod24**

### CODE REVIEW

**Review by AndrejMitrovic — APPROVED** [review]

**Review by kchulj — APPROVED** [review]
LG

**Comment by kchulj** [comment]
Why is `ldc-1.24.0` on ubuntu failing ..

**Comment by Geod24** [comment]
It's spurious.

**Comment by kchulj** [comment]
Will apply this commit to faucet's dependency.

**Pull request merged**
