### PR TITLE
Flash: Store a KeyPair instead of a Pair

### PR DESCRIPTION
**Pull request by Geod24**
We're moving away from `Pair`, and using `KeyPair` everywhere now,
since it contains the component of a `Pair` itself.
To keep the diff reviewable, this only affect places where `Pair`
was used. A later change will use `PublicKey` instead of `Point`.

### CODE REVIEW

**Review by kchulj — APPROVED** [review]
LGTM

**Comment by kchulj** [comment]
However, there is this log:
```
Could not print logs for node: Request to void geod24.LocalRest.RemoteAPI!(TestFlashAPI, Serializer).RemoteAPI.printLog() @safe couldn't be processed : base32.Base32Exception@submodules/base32/src/base32.d(1033): Invalid source length
308
```

**Review by linked0 — APPROVED** [review]

**Comment by Geod24** [comment]
> Could not print logs for node: Request to void geod24.LocalRest.RemoteAPI!(TestFlashAPI, Serializer).RemoteAPI.printLog() @safe couldn't be processed : base32.Base32Exception@submodules/base32/src/base32.d(1033): Invalid source length

Added a commit to fix this.

**Comment by kchulj** [comment]
Do we need to re-run the CI?

**Comment by Geod24** [comment]
Nope, something is wrong, need to debug

**Pull request merged**
