### PR TITLE
Revert timing changes to the test-suite

### PR DESCRIPTION
**Pull request by Geod24**
Just bisecting...

### CODE REVIEW

**Comment by Geod24** [comment]
So both Mac OSX job passed without needing a manual retry.
Mac OSX / LDC 1.26 passed first try, while `ldc-master` passed on second try. First failure was:
```
Module tests failed: agora.test.Flash
object.Exception@source/agora/test/Base.d(1191): TX (0x156017bbbabd10aec6ce7c76b1c019326dd4a993197bcf89bdddb85da5ba6f7d4778e8a5a1d831183139921976cb99dcb0aa1276b782656d6c95054bdde6225b) was not externalized in 3 blocks!
----------------
/Users/runner/work/agora/agora/source/agora/test/Base.d:1191 void agora.test.Base.TestAPIManager.expectTxExternalization(geod24.bitblob.BitBlob!(64uL).BitBlob, ulong) [0x10bf65b53]
/Users/runner/work/agora/agora/source/agora/test/Base.d:1176 void agora.test.Base.TestAPIManager.expectTxExternalization(agora.consensus.data.Transaction.Transaction, ulong) [0x10c126886]
/Users/runner/work/agora/agora/source/agora/test/Flash.d:819 void agora.test.Flash.__unittest_L711_C1() [0x10bface79]
/Users/runner/work/agora/agora/source/agora/test/Flash.d agora.test.Flash.__unittest [0x10c16f4fa]
/Users/runner/work/agora/agora/source/agora/test/Base.d:268 bool agora.test.Base.customModuleUnitTester().runTest(agora.test.Base.customModuleUnitTester().ModTest) [0x10c17d9ef]
/Users/runner/work/agora/agora/source/agora/test/Base.d:295 core.runtime.UnitTestResult agora.test.Base.customModuleUnitTester() [0x10bf4b51d]
runtime.d:607 runModuleUnitTests [0x10cddaab8]
dmain2.d:551 void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x10cdf4772]
dmain2.d:525 void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x10cdf46f2]
dmain2.d:584 _d_run_main2 [0x10cdf45ad]
dmain2.d:384 _d_run_main [0x10cdf4264]
/Users/runner/hostedtoolcache/dc/ldc2-1.26.0/x64/ldc2-1.26.0-osx-x86_64/bin/../import/core/internal/entrypoint.d:42 main [0x10c186e34]
```

Both Ubuntu jobs failed. `ldc-1.26.0` failures were:
```
Module tests failed: agora.test.LocalTransactions
core.exception.AssertError@source/agora/test/LocalTransactions.d(80): Check condition failed after timeout of 10 secs and 100 attempts: Node 0 has block height 0. Expected: 1
----------------
/home/runner/work/agora/agora/source/agora/utils/Utility.d:149 void agora.utils.Utility.retryFor!(core.exception.AssertError).retryFor(lazy bool, core.time.Duration, lazy immutable(char)[], immutable(char)[], ulong) [0x5645c00cb002]
/home/runner/work/agora/agora/source/agora/test/Base.d:648 void agora.test.Base.TestAPIManager.expectHeight!(std.range.iota!(const(ulong), const(ulong)).iota(const(ulong), const(ulong)).Result).expectHeight(std.range.iota!(const(ulong), const(ulong)).iota(const(ulong), const(ulong)).Result, agora.common.Types.Height, core.time.Duration, immutable(char)[], int).__lambda6!(ulong).__lambda6(ulong) [0x5645c0623a17]
```
```
Module tests failed: agora.test.LocalTransactions
object.Exception@submodules/localrest/source/geod24/LocalRest.d-mixin-1179(1203): Request timed-out
----------------
/home/runner/work/agora/agora/submodules/localrest/source/geod24/LocalRest.d-mixin-1179:1203 @safe ulong geod24.LocalRest.RemoteAPI!(agora.test.Base.TestAPI, agora.test.Base.Serializer).RemoteAPI.getBlockHeight() [0x55c52468d0da]
```

And `ldc-master`:
```
Module tests failed: agora.test.Flash
object.Exception@source/agora/test/Base.d(1191): TX (0xcb4762ed92aa5cc7b5c6094bca9ec09ecdf2e1d082c552c08f87fb7300f6d1bd97354c8cbd2a3894cff34237a1b49ef5033aeb333024754aade0a2f41b992725) was not externalized in 3 blocks!
----------------
source/agora/test/Base.d:1191 void agora.test.Base.TestAPIManager.expectTxExternalization(geod24.bitblob.BitBlob!(64uL).BitBlob, ulong) [0x55a59ef0f7cd]
source/agora/test/Base.d:1176 void agora.test.Base.TestAPIManager.expectTxExternalization(agora.consensus.data.Transaction.Transaction, ulong) [0x55a59f09ef04]
source/agora/test/Flash.d:704 void agora.test.Flash.__unittest_L609_C1() [0x55a59ef47b51]
source/agora/test/Flash.d [0x55a59f0def15]
```
```
Module tests failed: agora.test.ValidatorRecurringEnrollment
core.exception.AssertError@source/agora/test/ValidatorRecurringEnrollment.d(263): 6 != 5
----------------
source/agora/test/Base.d:169 nothrow void agora.test.Base.testAssertHandler(immutable(char)[], ulong, immutable(char)[]) [0x55f3e4f47316]
core/exception.d:448 onAssertErrorMsg [0x55f3e5ac9de1]
core/exception.d:590 _d_assert_msg [0x55f3e5aca175]
```

**Comment by hewison-chris** [comment]
`Module tests failed: agora.test.ValidatorRecurringEnrollment
core.exception.AssertError@source/agora/test/ValidatorRecurringEnrollment.d(263): 6 != 5`
Can be solved by https://github.com/bosagora/agora/pull/2401/commits/1350195094c8d109472df19e4358af0eb5241436 although it is worrying that it can take so long to get the other nodes to the expected height before the check for how many are enrolled.

**Comment by Geod24** [comment]
Added it.

**Comment by linked0** [comment]
Could you let me know why these commits are reverted?

**Comment by Geod24** [comment]
Sure, sorry, this should have been in the original message.
We saw an increase of CI failures in the last few days. This came, I believe, from @hewison-chris ' work on improving the test-suite. While it did make the test-suite faster, and some of the commits did make it more reliable, it also created an increase of failure on the Github CI.

Timing in those tests is a complicated problem. Since the machines have different capacities than our local one, something that would perform really well on your Mac might fail 80% of the time on Github CI, or the other way around. This is very obvious when you look at the Ubuntu runs vs the Mac runs, as the Ubuntu machines are usually faster, they tend to behave differently (not to mention the difference in the underlying system code).

I doubt all those commits are collectively at fault. It's likely that one or two of them cause most of the issues we're seeing. But since it is slowing down development quite a bit, I went with reverting all the timing changes in the hope that it will unblock other PRs, and we can tackle this problem in parallel.

**Pull request merged**
