### PR TITLE
Update LocalRest to increase fiber stack size

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
Previously the stack size of fibers in LocalRest were too small, they were changed to be 16MB by default.

### CODE REVIEW

**Comment by Geod24** [comment]
```
Running ./build/agora-unittests 
0   agora-unittests                     0x000000010fc3868e _D4core7runtime18runModuleUnitTestsUZ19unittestSegvHandlerUNbiPSQCk3sys5posix6signal9siginfo_tPvZv + 62
1   libsystem_platform.dylib            0x00007fff76800f5a _sigtramp + 26
2   agora-unittests                     0x000000010fc3dc01 _D4core6thread5Fiber5stateMxFNaNbNdNiNfZEQBnQBlQBh5State + 1
3   agora-unittests                     0x000000010f7c33f4 _D6geod249LocalRest18BaseFiberScheduler8dispatchMFZv + 228
4   agora-unittests                     0x000000010f7c320e _D6geod249LocalRest18BaseFiberScheduler5startMFDFZvZv + 46
5   agora-unittests                     0x000000010f5468d7 _D6geod249LocalRest__T9RemoteAPITC5agora4test4Base7TestAPIZQBl__T7spawnedTCQBpQBmQBk8TestNodeZQBdFSQCn6common6ConfigQhZv + 727
6   agora-unittests                     0x000000010f58edcf _D3std11concurrency__T6_spawnTPFS5agora6common6ConfigQhZvTQBaZQBoFbQBlQBmZ4execMFZv + 79
7   agora-unittests                     0x000000010fc3a385 thread_entryPoint + 373
8   libsystem_pthread.dylib             0x00007fff7680a6c1 _pthread_body + 340
9   libsystem_pthread.dylib             0x00007fff7680a56d _pthread_body + 0
Program exited with code -11
```

Another weird stack trace...

**Review by Geod24 — APPROVED** [review]
LGTM, merge at your convenience.

**Comment by AndrejMitrovic** [comment]
Yeah there seem to be somewhat random failures in Travis. I really thought the segfaults were finally resolved..

**Comment by AndrejMitrovic** [comment]
Part of https://github.com/bpfkorea/agora/issues/209

**Comment by AndrejMitrovic** [comment]
Blocked by https://github.com/bpfkorea/agora/pull/381 and https://github.com/Geod24/localrest/pull/23

**Comment by AndrejMitrovic** [comment]
Superseded by https://github.com/bpfkorea/agora/pull/379.

**Pull request closed without merging**
