### PR TITLE
Fix base-64 serialization for push APIs

### PR DESCRIPTION
**Pull request by AndrejMitrovic**

### CODE REVIEW

**Review by Geod24 — APPROVED** [review]

**Review by MichaelKim20 — APPROVED** [review]

**Comment by AndrejMitrovic** [comment]
Failure seems unrelated, CI is very flakey.

**Comment by AndrejMitrovic** [comment]
Merge button is gone too. Even with admin access?

**Comment by AndrejMitrovic** [comment]
I think with auto-merge turned on the merge button disappears.

**Comment by Geod24** [comment]
You have to disable auto-merge

**Pull request merged**
