### PR TITLE
Fix a timing issue in the Ledger unittest

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
This fixes another semi-frequent failure in our test-suite.

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
> No package file found in /root/agora/submodules/d2sqlite3/, expected one of dub.json/dub.sdl/package.json

This error in docker is something I experience occasionally when I build locally. But I'm not sure what's causing it. I thought maybe the reason is that I haven't added the submodule properly. But the `.gitmodules` looks ok, so I'm not sure..

**Comment by AndrejMitrovic** [comment]
Ok I see now that in docker it's not cloning the d2sqlite submodule. Maybe the built image is older than the commit `https://github.com/bpfkorea/agora/pull/137/commits/503a788871d3b10e1d055e7eb2ea95789efc6e02` which introduces the submodule?

**Comment by AndrejMitrovic** [comment]
I have a hunch what went wrong. Trying a fix now.

**Comment by AndrejMitrovic** [comment]
Great, the docker build failure is fixed.

**Comment by AndrejMitrovic** [comment]
@MukeunKim could you review & mark as approved so I can merge? Thank you.

**Review by andrej-mitrovic-sociomantic — APPROVED** [review]

**Pull request merged**
