### PR TITLE
Stats: Append scrape duration to the end of `/metrics` response

### PR DESCRIPTION
**Pull request by omerfirmak**

### CODE REVIEW

**Review by Geod24 — APPROVED** [review]

**Comment by Geod24** [comment]
Although https://dlang.org/phobos/std_datetime_stopwatch.html#StopWatch might be more suited

**Comment by omerfirmak** [comment]
> Although https://dlang.org/phobos/std_datetime_stopwatch.html#StopWatch might be more suited

this was what docs suggested

```
// If stopping or resetting the StopWatch is not required, then
// MonoTime can easily be used by itself without StopWatch.
auto before = MonoTime.currTime;
// do stuff...
auto timeElapsed = MonoTime.currTime - before;
```

**Comment by Geod24** [comment]
Looking at this again, I have to question the motive. Do you expect scrape to take long ?
I think that the delays you might be seeing is in Vibe.d handling the request, which means by the time we get to `MonoTime.start`, most of the delay has already passed.

**Comment by omerfirmak** [comment]
@Geod24, yeap I suspected the DB operations in `/metrics` to block the process for a long time occasionally. But havent seen anything proving that.

**Pull request merged**
