### PR TITLE
Config: Move generic code to submodule

### PR DESCRIPTION
**Pull request by Geod24**
Reduces the code size significantly with better isolation.

### CODE REVIEW

**Comment by Geod24** [comment]
Needs https://github.com/bosagora/faucet/pull/132

**Review by kchulj — APPROVED** [review]
Should LGTM since the submodule in faucet is merged now.

**Review by linked0 — APPROVED** [review]
LGTM

**Comment by Geod24** [comment]
Faucet compiles now :)

**Pull request merged**
