### PR TITLE
Update comment for validator keys 5 to 7

### PR DESCRIPTION
**Pull request by kchulj**
This is to match the new keys in #1248 .

### CODE REVIEW

**Comment by Geod24** [comment]
That doesn't sound right. Are you sure the issue wasn't on the infra side ?

**Comment by hewison-chris** [comment]
> That doesn't sound right. Are you sure the issue wasn't on the infra side ?

This is the comments inside the WK key pairs file. Looks like I did not update the comments there on the last update to a few keys.

**Comment by hewison-chris** [comment]
> > That doesn't sound right. Are you sure the issue wasn't on the infra side ?
> 
> This is the comments inside the WK key pairs file. Looks like I did not update the comments there on the last update to a few keys.

Oh there is more though. Now I am also not sure. Will take a look.

**Review by hewison-chris — CHANGES_REQUESTED** [review]
The bech32 addresses that are keys that give a sorted order for the Public key values are:-
boa1xzval2a3cdxv28n6slr62wlczslk3juvk7cu05qt3z55ty2rlfqfc6egsh2
boa1xzval3ah8z7ewhuzx6mywveyr79f24w49rdypwgurhjkr8z2ke2mycftv9n
boa1xzval4nvru2ej9m0rptq7hatukkavemryvct4f8smyy3ky9ct5u0s8w6gfy
boa1xrval5rzmma29zh4aqgv3mvcarhwa0w8rgthy3l9vaj3fywf9894ycmjkm8
boa1xrval6hd8szdektyz69fnqjwqfejhu4rvrpwlahh9rhaazzpvs5g6lh34l5
boa1xrval7gwhjz4k9raqukcnv2n4rl4fxt74m2y9eay6l5mqdf4gntnzhhscrh

**Comment by kchulj** [comment]
After a discussion with @hewison-chris , the keys in the agora side are correct. The keys in the infrastructure have to be updated.

**Pull request closed without merging**
