### PR TITLE
Add a system integration test based on docker-compose + various improvements

### PR DESCRIPTION
**Pull request by Geod24**
```
The system integration test spawns a network of 3 nodes
using `docker-compose`.
Eight transactions are sent, and we verify a block
has been created as a result.
```

We need to add support for code coverage but are currently blocked by #221

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
Nice work. I like it.

**Comment by Geod24** [comment]
Fixed file path

**Comment by Geod24** [comment]
Green

**Review by AndrejMitrovic — APPROVED** [review]

**Comment by AndrejMitrovic** [comment]
What happened to the code coverage bot?

**Pull request merged**
