### PR TITLE
Add ability to convert between QuorumConfig <-> SCPQuorumSet

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
Alternatively, we could replace QuorumConfig and use SCPQuorum directly? Let me know what you think.

### CODE REVIEW

**Comment by Geod24** [comment]
> Alternatively, we could replace QuorumConfig and use SCPQuorum directly?

Is there any downside to this ?

**Comment by AndrejMitrovic** [comment]
I can't think of any, other than depending more on SCP types.

**Comment by AndrejMitrovic** [comment]
Hmm well there is one problem, trying to make SCPQuorumSet immutable. Because everything in the `Config` has to be shared (to be used with LocalRest..).

**Comment by Geod24** [comment]
Or we could use the same trick we use with function arguments: JSON serialization.

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
