### PR TITLE
Separate 'runNode()' from main.d for use with the CLI as well

### PR DESCRIPTION
**Pull request by MichaelKim20**
I moved `runNode()` from `agora.node.main` to `agora.node.Node`.
The reason is to use `runNode()` in the CLI.

### CODE REVIEW

**Review by AndrejMitrovic — APPROVED** [review]

**Review by Geod24 — APPROVED** [review]
LGTM

**Review by TrustHenry — APPROVED** [review]
LGTM

**Comment by Geod24** [comment]
Part of #510

**Review by linked0 — APPROVED** [review]
LGTM

**Pull request merged**
