### PR TITLE
DNS: Merge two definitions of RDATA

### PR DESCRIPTION
**Pull request by Geod24**
```
The new union approach is superior, but some lingering declarations
were left behind.
```

I also did a few minor changes: using visibility qualifiers, adding / moving documentation, and renaming `cname` to just `name` as it's used by other records (e.g. `NS`).

### CODE REVIEW

**Review by mkykadir — APPROVED** [review]

**Comment by omerfirmak** [comment]
This apparently broke docker build

```
source/agora/common/DNS.d(670,13): Error: field `RDATA.a` cannot access pointers in `@safe` code that overlap other fields
source/agora/common/DNS.d(675,13): Error: field `RDATA.name` cannot access pointers in `@safe` code that overlap other fields
source/agora/common/DNS.d(680,13): Error: field `RDATA.soa` cannot access pointers in `@safe` code that overlap other fields
Type 'FlashControlAPI' implements more than one interface: make sure the one describing the REST server is the first one
```

**Comment by linked0** [comment]
It needs to upgrade the `ldc2` to the latest version.

**Comment by omerfirmak** [comment]
> It needs to upgrade the `ldc2` to the latest version.

Weirdly, it is already on v.1.28.0

**Comment by linked0** [comment]
I had the same problem on the local machine yesterday. I solved the problem with `brew update & brew upgrade`, so I thought the version was old. But it could be aroused from another cause, I guess.

**Comment by mkykadir** [comment]
Actual PR that added mentioned code is #2711 BTW, it didn't throw any errors on my machine

**Comment by Geod24** [comment]
As discussed on Slack, it was an outdated `agora-builder` locally.

**Pull request merged**
