### PR TITLE
Tx signature verification unittest

### PR DESCRIPTION
**Pull request by TrustHenry**
This creates a new transaction and signs it as a publickey
of the previous transaction to create and validate the input.
Required PR : Implement transaction verification #60

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
There's a few issues with this PR:

- The test code should not live here. It should live in `agora.common.Transaction` because it is self-contained and doesn't require networking code.
- It does not need the "TransactionManager"
- It doesn't seem to use the public key in the `outputs` array for testing the signature, instead it directly uses the key in the key_pairs array (`PublicKey pubkey = key_pairs[0].address; assert(pubkey.verify(input.signature, inputHash[]));`).

So I suggest moving unittest code to `agora.common.Transaction`, and writing something similar to:

```D
/// This creates a new transaction and signs it as a publickey
/// of the previous transaction to create and validate the input.
unittest
{
    immutable(KeyPair)[] key_pairs;
    key_pairs ~= KeyPair.random();
    key_pairs ~= KeyPair.random();

    // first transaction (coinbase to first public key)
    Transaction tx0 =
    {
        inputs  : [Input(Hash.init, 0)],
        outputs : [Output(40_000, key_pairs[0].address)]
    };

    Input input =
    {
        previous : hashFull(tx0),  // hash of previous utxo
        index : 0  // first item in the outputs array
    };

    // Signs the previous hash value.
    Signature signature = key_pairs[0].secret.sign(hashFull(input)[]);
    input.signature = signature;

    Output output =
    {
        value : 20_000,
        address : key_pairs[1].address,
    };

    // second transaction (spends the utxo from the first transaction)
    Transaction tx1 =
    {
        inputs : [input],
        outputs : [output]
    };

    // Verify the transaction's only output
    assert(tx0.outputs[0].address.verify(
        tx1.inputs[0].signature,
        hashFull(tx1.inputs[0])[]));
}
```

@Geod24 please verify my logic in this unittest. But I think it should be reasonable..

**Comment by HenryXtremer** [comment]
@AndrejMitrovic `agora.common.Transaction` You're talking about me adding it to this file?

**Comment by TrustHenry** [comment]
@AndrejMitrovic `agora.common.Transaction` You're talking about me adding it to this file?

**Comment by AndrejMitrovic** [comment]
Yes to move the unittest there. The `source/agora/test` folder is only for code that needs networking support.

**Comment by TrustHenry** [comment]
I uploaded it again. I'll close this PR.

**Pull request closed without merging**
