### PR TITLE
Simplify createNewNode()

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
The address was already accessible through the public key.

Simplification as part of #785

### CODE REVIEW

**Comment by Geod24** [comment]
What about full nodes ?

**Comment by AndrejMitrovic** [comment]
Good catch. This means currently we still generate a keypair for full nodes. This will need to be fixed.

**Comment by AndrejMitrovic** [comment]
I'd even say that we should remove `is_validator`. If there is a `key_pair`, the node is a validator.

**Comment by TrustHenry** [comment]
> I'd even say that we should remove `is_validator`. If there is a `key_pair`, the node is a validator.

if there is a key_pair, I think it can be a validator.
But What if a node wants to stop the consensus when it's a validator?
Some reasons (upgrade, maintenance, withdrawal of funds, etc.)

**Comment by AndrejMitrovic** [comment]
Good thinking @TrustHenry.

**Comment by AndrejMitrovic** [comment]
Updated. I've simplified it again, improved the addressing and refactored some code. It should be much better and more correct.

The logs are much nicer now. For example:

```
Log for node Validator #2 (GA44...6FRQ):
======================================================================
2020-05-08 10:55:17,500 Info [agora.node.FullNode] - Doing network discovery..
2020-05-08 10:55:17,500 Trace [agora.common.BanManager] - BanManager: Address Validator #2 (GA44...6FRQ) banned until 9223372036854775807
2020-05-08 10:55:17,500 Info [agora.network.NetworkManager] - Discovering from { r: { impl: 0X000000011106C8C0, idx: 1 } }
2020-05-08 10:55:17,500 Info [agora.network.NetworkManager] - Connecting to next set of addresses: ["Validator #1 (GBZX...O3WC)", "Validator #0 (GAQJ...GBDP)"]
```

And for full nodes I just use a sequence without the public key:

```
Log for node FullNode #0:
======================================================================
2020-05-08 10:59:21,78 [32mInfo[0m [agora.node.FullNode] - Doing network discovery..
```

This should make it much easier to debug test-suite failures.

**Review by Geod24 — APPROVED** [review]
Sweeeeeeeeet

**Comment by AndrejMitrovic** [comment]
There was a bug in my code. I added another commit which makes it easier to see which logs are being printed out. It helped me find the bug.

**Review by TrustHenry — APPROVED** [review]
Nice! It has become easier to distinguish nodes.

**Pull request merged**
