### PR TITLE
Reduce the number of txs created in a test

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
tl;dr: too many fibers probably

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
Btw, if I increase the number of blocks to 1000 (so 8000 transactions), the test seems to just hang on my machine. So there is a limit reached for sure.

**Comment by AndrejMitrovic** [comment]
:green_apple:

Let's see if the failures now magically disappear in v0.x.x.

If they do, we should file an issue for what is likely a fiber limit problem that we can look into later. Also, we need much better management of requests. Spawning a fiber for every transaction with no delay could be seen as a vector for a DoS attack.

**Review by Geod24 — APPROVED** [review]

**Comment by Geod24** [comment]
There was a failure:
```
Running ./build/agora 
Filtered method 'getBlockHeight()'
Filtered method 'getBlockHeight()'
Filtered method 'getBlockHeight()'
Filtered method 'getBlockHeight()'
Filtered method 'getBlockHeight()'
Filtered method 'getBlockHeight()'
Filtered method 'getBlockHeight()'
Filtered method 'getBlockHeight()'
Filtered method 'getBlockHeight()'
"Request timed-out"
core.exception.AssertError@source/agora/test/Ledger.d(59): Node 3 has block height 87. Expected: 88
----------------
??:? _d_assert_msg [0x10a622186]
Ledger.d:59 @safe void agora.test.Ledger.__unittest_L29_C1().__lambda2!(ulong, geod24.LocalRest.RemoteAPI!(agora.test.Base.TestAPI).RemoteAPI).__lambda2(ulong, geod24.LocalRest.RemoteAPI!(agora.test.Base.TestAPI).RemoteAPI) [0x109fb1bd9]
iteration.d:971 @safe std.typecons.Flag!("each").Flag std.algorithm.iteration.each!(agora.test.Ledger.__unittest_L29_C1().__lambda2).each!(std.range.enumerate!(ulong, geod24.LocalRest.RemoteAPI!(agora.test.Base.TestAPI).RemoteAPI[]).enumerate(geod24.LocalRest.RemoteAPI!(agora.test.Base.TestAPI).RemoteAPI[], ulong).Result).each(std.range.enumerate!(ulong, geod24.LocalRest.RemoteAPI!(agora.test.Base.TestAPI).RemoteAPI[]).enumerate(geod24.LocalRest.RemoteAPI!(agora.test.Base.TestAPI).RemoteAPI[], ulong).Result) [0x109fada2c]
Ledger.d:58 void agora.test.Ledger.__unittest_L29_C1() [0x109fad1d7]
Ledger.d:0 agora.test.Ledger.__unittest [0x109fb2015]
??:? int core.runtime.runModuleUnitTests().__foreachbody2(object.ModuleInfo*) [0x10a626efa]
??:? int rt.minfo.moduleinfos_apply(scope int delegate(immutable(object.ModuleInfo*))).__foreachbody2(ref rt.sections_elf_shared.DSO) [0x10a64cc81]
??:? int rt.sections_elf_shared.DSO.opApply(scope int delegate(ref rt.sections_elf_shared.DSO)) [0x10a64d799]
??:? int rt.minfo.moduleinfos_apply(scope int delegate(immutable(object.ModuleInfo*))) [0x10a64cc2b]
??:? int object.ModuleInfo.opApply(scope int delegate(object.ModuleInfo*)) [0x10a63a56e]
??:? runModuleUnitTests [0x10a626caf]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x10a64492e]
??:? _d_run_main [0x10a644772]
__entrypoint.d:8 main [0x109fc03f4]
1/24 unittests FAILED
Program exited with code 1
The command "dub test -b unittest-cov --skip-registry=all --compiler=${DC}" exited with 2.
```

**Comment by Geod24** [comment]
```
Running ./build/agora 
Filtered method 'getBlockHeight()'
Filtered method 'getBlockHeight()'
Filtered method 'getBlockHeight()'
Filtered method 'getBlockHeight()'
Filtered method 'getBlockHeight()'
Filtered method 'getBlockHeight()'
Filtered method 'getBlockHeight()'
Filtered method 'getBlockHeight()'
Filtered method 'getBlockHeight()'
Filtered method 'getBlockHeight()'
"Request timed-out"
0   agora                               0x000000010348e4ee _D4core7runtime18runModuleUnitTestsUZ19unittestSegvHandlerUNbiPSQCk3sys5posix6signal9siginfo_tPvZv + 62
1   libsystem_platform.dylib            0x00007fff7aff8f5a _sigtramp + 26
Program exited with code -11
The command "dub test -b unittest-cov --skip-registry=all --compiler=${DC}" exited with 2.
```

Segfaulted again ;(

**Pull request merged**
