### PR TITLE
System test: Resolve agora module dependencies for SCP.

### PR DESCRIPTION
**Pull request by MichaelKim20**
This has created a solution to issue #578 **CircleCI frequently fails...**

We need to resolve module dependencies to use SCPs in system testing.
I have added a dependent module for the system test.
And I set up SCP C++Module to pre-build.
It will be the solution for PR #637
Relates #578

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
> It will be the solution for PR #637

A solution for what problem in PR #637?

**Comment by MichaelKim20** [comment]
> > It will be the solution for PR #637
> 
> A solution for what problem in PR #637?

@AndrejMitrovic This has created a solution to issue #578 .
So it is to solve the problem with CircleCI.
PR #637 has no problem at all. It will solve the error in CircleCI.
If it is merged first, everything will be solved.

**Comment by Geod24** [comment]
I don't understand. The system tests are not using SCP (and they should not). If something was missing from `dub.json`, the compilation would fail. How is this solving #578 ?

**Comment by MichaelKim20** [comment]
> I don't understand. The system tests are not using SCP (and they should not). If something was missing from `dub.json`, the compilation would fail. How is this solving #578 ?

PR #637 has a commit '365c9dd'.
In agora.utils.PrettyPrinter, use the following:
```
import scpd.Cpp;
import scpd.types.Stellar_SCP;
import scpd.types.Stellar_types : StellarHash = Hash;
```

**Comment by MichaelKim20** [comment]
https://github.com/bpfkorea/agora/blob/365c9dd1beec83629b173c0ed78fb5573d782b04/source/agora/utils/PrettyPrinter.d#L32-L34

**Comment by MichaelKim20** [comment]
**I executed the following command.**
```
cd tests/system
dub
```

**I first saw this error message.**

../../source/agora/common/Config.d(26,8): Error: module node is in file 'dyaml/node.d' which cannot be read

**So, I added the following to the file `tests/system/dub.selections.json`.**
```
	"dyaml": {"path":"../../submodules/dyaml/"},
```

**Then, I added the following to the file `tests/system/dub.json`.**
```
       	"dyaml":            { "path": "../../submodules/dyaml/", "version": "*" },
```

**After that, I ran the test again. This time I could see the following message.**
```
Undefined symbols for architecture x86_64:
  "__D4scpd3Cpp12__ModuleInfoZ", referenced from:
      __D5agora5utils13PrettyPrinter12__ModuleInfoZ in systemtest-simple.o
  "__D4scpd3Cpp__T10shared_ptrTSQBa5types11Stellar_SCP12SCPQuorumSetZQBz8opAssignMFNaNbNcNiNjSQDkQDi__TQDhTQCyZQDpZQw", referenced from:
      __D5agora5utils13PrettyPrinter9QuorumFmt8toStringMFNbNeMDFNfMAxaZvZv in systemtest-simple.o
  "__D4scpd3Cpp__T6vectorTSQv5types11Stellar_SCP12SCPQuorumSetTSQCgQCe__T9allocatorTQCgZQpZQCv8opEqualsMxFNaNbNiNfKxSQEhQEf__TQEeTQEaTQCtZQEqZb", referenced from:
      __D4scpd5types7XDRBase__T7xvectorTSQBgQBe11Stellar_SCP12SCPQuorumSetVki4294967292ZQCf11__xopEqualsFKxSQDvQDtQDq__TQDlTQDgVki4294967292ZQEgKxQBnZb in systemtest-simple.o
  "__D4scpd3Cpp__T6vectorTSQv5types13Stellar_types9PublicKeyTSQCeQCc__T9allocatorTQCeZQpZQCt8opEqualsMxFNaNbNiNfKxSQEfQEd__TQEcTQDyTQCtZQEoZb", referenced from:
      __D4scpd5types7XDRBase__T7xvectorTSQBgQBe13Stellar_types9PublicKeyVki4294967292ZQCd11__xopEqualsFKxSQDtQDrQDo__TQDjTQDeVki4294967292ZQEeKxQBnZb in systemtest-simple.o
  "__D4scpd3Cpp__T6vectorTSQv5types7XDRBase__T7xvectorThVki4294967292ZQyTSQCqQCo__T9allocatorTQCqZQpZQDf7opSliceMNgFNaNbNiNfZNgASQEtQDzQDw__TQDrThVki4294967292ZQEk", referenced from:
      __D5agora5utils13PrettyPrinter16SCPNominationFmt8toStringMFNbNeMDFNfMAxaZvZv in systemtest-simple.o
  "__D4scpd3Cpp__T6vectorTSQv5types7XDRBase__T7xvectorThVki4294967292ZQyTSQCqQCo__T9allocatorTQCqZQpZQDf8opEqualsMxFNaNbNiNfKxSQErQEp__TQEoTQEkTQCtZQFaZb", referenced from:
      __D5agora5utils13PrettyPrinter16SCPNominationFmt11__xopEqualsFKxSQCkQChQCeQBsKxQpZb in systemtest-simple.o
      __D4scpd5types7XDRBase__T7xvectorTSQBgQBeQBb__TQwThVki4294967292ZQBoVki4294967292ZQCf11__xopEqualsFKxSQDvQDtQDq__TQDlTQDgVki4294967292ZQEgKxQBnZb in systemtest-simple.o
  "__D4scpd3Cpp__T6vectorThTSQxQu__T9allocatorThZQnZQBi7opSliceMNgFNaNbNiNfZNgAh", referenced from:
      __D5agora5utils13PrettyPrinter12SCPBallotFmt8toStringMFNbNeMDFNfMAxaZvZv in systemtest-simple.o
      __D5agora5utils13PrettyPrinter14SCPEnvelopeFmt8toStringMFNbNfMDFNfMAxaZvZv in systemtest-simple.o
      __D5agora5utils13PrettyPrinter16SCPNominationFmt8toStringMFNbNeMDFNfMAxaZvZ__T9__lambda2TxS4scpd5types7XDRBase__T7xvectorThVki4294967292ZQyZQCkFxQCdZSQFrQFoQFl16ConsensusDataFmt in systemtest-simple.o
      __D5agora5utils13PrettyPrinter16SCPNominationFmt8toStringMFNbNeMDFNfMAxaZvZ__T9__lambda3TxS4scpd5types7XDRBase__T7xvectorThVki4294967292ZQyZQCkFxQCdZSQFrQFoQFl16ConsensusDataFmt in systemtest-simple.o
  "__D4scpd3Cpp__T6vectorThTSQxQu__T9allocatorThZQnZQBi8opEqualsMxFNaNbNiNfKxSQCuQCs__TQCrThTQCnZQDbZb", referenced from:
      __D4core8internal5array8equality__T8__equalsTxS4scpd5types7XDRBase__T7xvectorThVki4294967292ZQyTxQBzZQCoFNaNbNiNfAxQCrQfZb in systemtest-simple.o
      __D4scpd5types7XDRBase__T7xvectorThVki4294967292ZQy11__xopEqualsFKxSQCnQClQCi__TQCdThVki4294967292ZQCwKxQBlZb in systemtest-simple.o
      __D5agora5utils13PrettyPrinter12SCPBallotFmt11__xopEqualsFKxSQCgQCdQCaQBoKxQpZb in systemtest-simple.o
      __D5agora5utils13PrettyPrinter10PrepareFmt11__xopEqualsFKxSQCeQCbQByQBmKxQpZb in systemtest-simple.o
      __D5agora5utils13PrettyPrinter10ConfirmFmt11__xopEqualsFKxSQCeQCbQByQBmKxQpZb in systemtest-simple.o
      __D5agora5utils13PrettyPrinter14ExternalizeFmt11__xopEqualsFKxSQCiQCfQCcQBqKxQpZb in systemtest-simple.o
      __D5agora5utils13PrettyPrinter14SCPEnvelopeFmt11__xopEqualsFKxSQCiQCfQCcQBqKxQpZb in systemtest-simple.o
      ...
  "__D4scpd5types11Stellar_SCP11SCPEnvelope11__xopEqualsFKxSQCcQCaQBxQBnKxQpZb", referenced from:
      __D47TypeInfo_S4scpd5types11Stellar_SCP11SCPEnvelope6__initZ in systemtest-simple.o
  "__D4scpd5types11Stellar_SCP11SCPEnvelope9__xtoHashFNbNeKxSQCdQCbQByQBoZm", referenced from:
      __D47TypeInfo_S4scpd5types11Stellar_SCP11SCPEnvelope6__initZ in systemtest-simple.o
  "__D4scpd5types11Stellar_SCP12SCPQuorumSet11__xopEqualsFKxSQCdQCbQByQBoKxQpZb", referenced from:
      __D48TypeInfo_S4scpd5types11Stellar_SCP12SCPQuorumSet6__initZ in systemtest-simple.o
  "__D4scpd5types11Stellar_SCP12SCPQuorumSet9__xtoHashFNbNeKxSQCeQCcQBzQBpZm", referenced from:
      __D48TypeInfo_S4scpd5types11Stellar_SCP12SCPQuorumSet6__initZ in systemtest-simple.o
  "__D4scpd5types11Stellar_SCP12SCPStatement10_pledges_t10_confirm_t11__xopEqualsFKxSQDbQCzQCwQCmQCbQBsKxQvZb", referenced from:
      __D72TypeInfo_S4scpd5types11Stellar_SCP12SCPStatement10_pledges_t10_confirm_t6__initZ in systemtest-simple.o
  "__D4scpd5types11Stellar_SCP12SCPStatement10_pledges_t10_confirm_t9__xtoHashFNbNeKxSQDcQDaQCxQCnQCcQBtZm", referenced from:
      __D72TypeInfo_S4scpd5types11Stellar_SCP12SCPStatement10_pledges_t10_confirm_t6__initZ in systemtest-simple.o
  "__D4scpd5types11Stellar_SCP12SCPStatement10_pledges_t10_prepare_t11__xopEqualsFKxSQDbQCzQCwQCmQCbQBsKxQvZb", referenced from:
      __D72TypeInfo_S4scpd5types11Stellar_SCP12SCPStatement10_pledges_t10_prepare_t6__initZ in systemtest-simple.o
  "__D4scpd5types11Stellar_SCP12SCPStatement10_pledges_t10_prepare_t9__xtoHashFNbNeKxSQDcQDaQCxQCnQCcQBtZm", referenced from:
      __D72TypeInfo_S4scpd5types11Stellar_SCP12SCPStatement10_pledges_t10_prepare_t6__initZ in systemtest-simple.o
  "__D4scpd5types11Stellar_SCP12SCPStatement10_pledges_t14_externalize_t11__xopEqualsFKxSQDfQDdQDaQCqQCfQBwKxQvZb", referenced from:
      __D76TypeInfo_S4scpd5types11Stellar_SCP12SCPStatement10_pledges_t14_externalize_t6__initZ in systemtest-simple.o
  "__D4scpd5types11Stellar_SCP12SCPStatement10_pledges_t14_externalize_t9__xtoHashFNbNeKxSQDgQDeQDbQCrQCgQBxZm", referenced from:
      __D76TypeInfo_S4scpd5types11Stellar_SCP12SCPStatement10_pledges_t14_externalize_t6__initZ in systemtest-simple.o
  "__D4scpd5types11Stellar_SCP12SCPStatement10_pledges_t8toStringMxFNeZAya", referenced from:
      __D60TypeInfo_S4scpd5types11Stellar_SCP12SCPStatement10_pledges_t6__initZ in systemtest-simple.o
  "__D4scpd5types11Stellar_SCP12SCPStatement11__xopEqualsFKxSQCdQCbQByQBoKxQpZb", referenced from:
      __D48TypeInfo_S4scpd5types11Stellar_SCP12SCPStatement6__initZ in systemtest-simple.o
  "__D4scpd5types11Stellar_SCP12SCPStatement9__xtoHashFNbNeKxSQCeQCcQBzQBpZm", referenced from:
      __D48TypeInfo_S4scpd5types11Stellar_SCP12SCPStatement6__initZ in systemtest-simple.o
  "__D4scpd5types11Stellar_SCP12__ModuleInfoZ", referenced from:
      __D5agora5utils13PrettyPrinter12__ModuleInfoZ in systemtest-simple.o
  "__D4scpd5types11Stellar_SCP13SCPNomination11__xopEqualsFKxSQCeQCcQBzQBpKxQpZb", referenced from:
      __D49TypeInfo_S4scpd5types11Stellar_SCP13SCPNomination6__initZ in systemtest-simple.o
  "__D4scpd5types11Stellar_SCP13SCPNomination9__xtoHashFNbNeKxSQCfQCdQCaQBqZm", referenced from:
      __D49TypeInfo_S4scpd5types11Stellar_SCP13SCPNomination6__initZ in systemtest-simple.o
  "__D4scpd5types11Stellar_SCP9SCPBallot11__xopEqualsFKxSQBzQBxQBuQBkKxQpZb", referenced from:
      __D44TypeInfo_S4scpd5types11Stellar_SCP9SCPBallot6__initZ in systemtest-simple.o
  "__D4scpd5types11Stellar_SCP9SCPBallot9__xtoHashFNbNeKxSQCaQByQBvQBlZm", referenced from:
      __D44TypeInfo_S4scpd5types11Stellar_SCP9SCPBallot6__initZ in systemtest-simple.o
  "__D4scpd5types13Stellar_types12__ModuleInfoZ", referenced from:
      __D5agora5utils13PrettyPrinter12__ModuleInfoZ in systemtest-simple.o
  "__D4scpd5types13Stellar_types9PublicKey11__xopEqualsFKxSQCbQBzQBwQBkKxQpZb", referenced from:
      __D46TypeInfo_S4scpd5types13Stellar_types9PublicKey6__initZ in systemtest-simple.o
  "__D4scpd5types13Stellar_types9PublicKey9__xtoHashFNbNeKxSQCcQCaQBxQBlZm", referenced from:
      __D46TypeInfo_S4scpd5types13Stellar_types9PublicKey6__initZ in systemtest-simple.o
  "__D5agora6common6Config12__ModuleInfoZ", referenced from:
      __D5agora5utils13PrettyPrinter12__ModuleInfoZ in systemtest-simple.o
  "__D5agora6common6Config14toQuorumConfigFKxS4scpd5types11Stellar_SCP12SCPQuorumSetZSQDcQCzQCv12QuorumConfig", referenced from:
      __D5agora5utils13PrettyPrinter9QuorumFmt8toStringMFNbNeMDFNfMAxaZvZv in systemtest-simple.o
  "__D5agora9consensus4data13ConsensusData12__ModuleInfoZ", referenced from:
      __D5agora5utils13PrettyPrinter12__ModuleInfoZ in systemtest-simple.o
  "__D5agora9consensus4data13ConsensusDataQp11__xopEqualsFKxSQCdQCaQBtQBrQBuKxQsZb", referenced from:
      __D48TypeInfo_S5agora9consensus4data13ConsensusDataQp6__initZ in systemtest-simple.o
  "__D5agora9consensus4data13ConsensusDataQp9__xtoHashFNbNeKxSQCeQCbQBuQBsQBvZm", referenced from:
      __D48TypeInfo_S5agora9consensus4data13ConsensusDataQp6__initZ in systemtest-simple.o
ld: symbol(s) not found for architecture x86_64
```

I analyzed the above error output. The analysis results were as follows.
```
Undefined symbols for architecture x86_64:
  "scpd.Cpp12__ModuleInfoZ", referenced from:
      agora.utils.PrettyPrinter.__ModuleInfoZ in systemtest-simple.o
  "scpd.types.Stellar_SCP.SCPQuorumSet.Assign", referenced from:
      agora.utils.PrettyPrinter.QuorumFmt.toString. in systemtest-simple.o
  "scpd.types.Stellar_SCP.SCPQuorumSetTSQCgQCe__T9allocatorTQCgZQpZQCv13ConstIterator5emptyMxFNaNbNdNiNfZb", referenced from:
      agora.common.Config.toQuorumConfig.scpd.types.Stellar_SCP.SCPQuorumSet.QuorumConfig in systemtest-simple.o
  "scpd.types.Stellar_SCP.SCPQuorumSetTSQCgQCe__T9allocatorTQCgZQpZQCv13ConstIterator5frontMxFNaNbNcNiNfZxSQEvQEbQDyQDo", referenced from:
      agora.common.Config.toQuorumConfig.scpd.types.Stellar_SCP.SCPQuorumSet.QuorumConfig in systemtest-simple.o
  "scpd.types.Stellar_SCP.SCPQuorumSetTSQCgQCe__T9allocatorTQCgZQpZQCv13ConstIterator8popFrontMFNaNbNiZv", referenced from:
      agora.common.Config.toQuorumConfig.scpd.types.Stellar_SCP.SCPQuorumSet.QuorumConfig in systemtest-simple.o
  "scpd.types.Stellar_SCP.SCPQuorumSetTSQCgQCe__T9allocatorTQCgZQpZQCv13constIteratorMxFNaNbNiNfZSQEmQEk__TQEjTQEfTQCyZQEv13ConstIterator", referenced from:
      agora.common.Config.toQuorumConfig.scpd.types.Stellar_SCP.SCPQuorumSet.QuorumConfig in systemtest-simple.o
  "scpd.types.Stellar_SCP.SCPQuorumSetTSQCgQCe__T9allocatorTQCgZQpZQCv8opEqualsMxFNaNbNiNfKxSQEhQEf__TQEeTQEaTQCtZQEqZb", referenced from:
      scpd.types.XDRBase__T7xvectorTSQBgQBe11Stellar_SCP.SCPQuorumSetVki4294967292ZQCf11__xopEqualsFKxSQDvQDtQDq__TQDlTQDgVki4294967292ZQEgKxQBnZb in systemtest-simple.o
  "scpd.types.Stellar_types.PublicKeyTSQCeQCc__T9allocatorTQCeZQpZQCt13ConstIterator5emptyMxFNaNbNdNiNfZb", referenced from:
      agora.common.Config.toQuorumConfig.scpd.types.Stellar_SCP.SCPQuorumSet.QuorumConfig in systemtest-simple.o
  "scpd.types.Stellar_types.PublicKeyTSQCeQCc__T9allocatorTQCeZQpZQCt13ConstIterator5frontMxFNaNbNcNiNfZxSQEtQDzQDwQDk", referenced from:
      agora.common.Config.toQuorumConfig.scpd.types.Stellar_SCP.SCPQuorumSet.QuorumConfig in systemtest-simple.o
  "scpd.types.Stellar_types.PublicKeyTSQCeQCc__T9allocatorTQCeZQpZQCt13ConstIterator8popFrontMFNaNbNiZv", referenced from:
      agora.common.Config.toQuorumConfig.scpd.types.Stellar_SCP.SCPQuorumSet.QuorumConfig in systemtest-simple.o
  "scpd.types.Stellar_types.PublicKeyTSQCeQCc__T9allocatorTQCeZQpZQCt13constIteratorMxFNaNbNiNfZSQEkQEi__TQEhTQEdTQCyZQEt13ConstIterator", referenced from:
      agora.common.Config.toQuorumConfig.scpd.types.Stellar_SCP.SCPQuorumSet.QuorumConfig in systemtest-simple.o
  "scpd.types.Stellar_types.PublicKeyTSQCeQCc__T9allocatorTQCeZQpZQCt8opEqualsMxFNaNbNiNfKxSQEfQEd__TQEcTQDyTQCtZQEoZb", referenced from:
      scpd.types.XDRBase__T7xvectorTSQBgQBe13Stellar_types.PublicKeyVki4294967292ZQCd11__xopEqualsFKxSQDtQDrQDo__TQDjTQDeVki4294967292ZQEeKxQBnZb in systemtest-simple.o
  "scpd.types.XDRBase__T7xvectorThVki4294967292ZQyTSQCqQCo__T9allocatorTQCqZQpZQDf7opSliceMNgFNaNbNiNfZNgASQEtQDzQDw__TQDrThVki4294967292ZQEk", referenced from:
      agora.utils.PrettyPrinter.SCPNominationFmt8toString. in systemtest-simple.o
  "scpd.types.XDRBase__T7xvectorThVki4294967292ZQyTSQCqQCo__T9allocatorTQCqZQpZQDf8opEqualsMxFNaNbNiNfKxSQErQEp__TQEoTQEkTQCtZQFaZb", referenced from:
      scpd.types.XDRBase__T7xvectorTSQBgQBeQBb__TQwThVki4294967292ZQBoVki4294967292ZQCf11__xopEqualsFKxSQDvQDtQDq__TQDlTQDgVki4294967292ZQEgKxQBnZb in systemtest-simple.o
      agora.utils.PrettyPrinter.SCPNominationFmt11__xopEqualsFKxSQCkQChQCeQBsKxQpZb in systemtest-simple.o
  "scpd.vectorThTSQxQu__T9allocatorThZQnZQBi7opSliceMNgFNaNbNiNfZNgAh", referenced from:
      agora.utils.PrettyPrinter.SCPBallotFmt.toString. in systemtest-simple.o
      agora.utils.PrettyPrinter.SCPEnvelopeFmt8toStringMFNbNfMDFNfMAxaZvZv in systemtest-simple.o
      agora.utils.PrettyPrinter.SCPNominationFmt8toStringMFNbNeMDFNfMAxaZvZ__T9__lambda2TxS4scpd.types.XDRBase__T7xvectorThVki4294967292ZQyZQCkFxQCdZSQFrQFoQFl16ConsensusDataFmt in systemtest-simple.o
      agora.utils.PrettyPrinter.SCPNominationFmt8toStringMFNbNeMDFNfMAxaZvZ__T9__lambda3TxS4scpd.types.XDRBase__T7xvectorThVki4294967292ZQyZQCkFxQCdZSQFrQFoQFl16ConsensusDataFmt in systemtest-simple.o
  "scpd.vectorThTSQxQu__T9allocatorThZQnZQBi8opEqualsMxFNaNbNiNfKxSQCuQCs__TQCrThTQCnZQDbZb", referenced from:
      scpd.types.XDRBase__T7xvectorThVki4294967292ZQy11__xopEqualsFKxSQCnQClQCi__TQCdThVki4294967292ZQCwKxQBlZb in systemtest-simple.o
      core8internal5array8equality__T8__equalsTxS4scpd.types.XDRBase__T7xvectorThVki4294967292ZQyTxQBzZQCoFNaNbNiNfAxQCrQfZb in systemtest-simple.o
      scpd.types.XDRBase__T7xvectorThVki64ZQq11__xopEqualsFKxSQCfQCdQCa__TQBvThVki64ZQCgKxQBdZb in systemtest-simple.o
      agora.utils.PrettyPrinter.SCPBallotFmt11__xopEqualsFKxSQCgQCdQCaQBoKxQpZb in systemtest-simple.o
      agora.utils.PrettyPrinter.PrepareFmt11__xopEqualsFKxSQCeQCbQByQBmKxQpZb in systemtest-simple.o
      agora.utils.PrettyPrinter.ConfirmFmt11__xopEqualsFKxSQCeQCbQByQBmKxQpZb in systemtest-simple.o
      agora.utils.PrettyPrinter.ExternalizeFmt11__xopEqualsFKxSQCiQCfQCcQBqKxQpZb in systemtest-simple.o
      ...
  "scpd.types.Stellar_SCP11SCPEnvelope11__xopEqualsFKxSQCcQCaQBxQBnKxQpZb", referenced from:
      7TypeInfo_S4scpd.types.Stellar_SCP11SCPEnvelope6__initZ in systemtest-simple.o
  "scpd.types.Stellar_SCP11SCPEnvelope9__xtoHashFNbNeKxSQCdQCbQByQBoZm", referenced from:
      7TypeInfo_S4scpd.types.Stellar_SCP11SCPEnvelope6__initZ in systemtest-simple.o
  "scpd.types.Stellar_SCP.SCPQuorumSet11__xopEqualsFKxSQCdQCbQByQBoKxQpZb", referenced from:
      8TypeInfo_S4scpd.types.Stellar_SCP.SCPQuorumSet6__initZ in systemtest-simple.o
  "scpd.types.Stellar_SCP.SCPQuorumSet9__xtoHashFNbNeKxSQCeQCcQBzQBpZm", referenced from:
      8TypeInfo_S4scpd.types.Stellar_SCP.SCPQuorumSet6__initZ in systemtest-simple.o
  "scpd.types.Stellar_SCP.SCPStatement10_pledges_t10_confirm_t11__xopEqualsFKxSQDbQCzQCwQCmQCbQBsKxQvZb", referenced from:
      __D72TypeInfo_S4scpd.types.Stellar_SCP.SCPStatement10_pledges_t10_confirm_t6__initZ in systemtest-simple.o
  "scpd.types.Stellar_SCP.SCPStatement10_pledges_t10_confirm_t9__xtoHashFNbNeKxSQDcQDaQCxQCnQCcQBtZm", referenced from:
      __D72TypeInfo_S4scpd.types.Stellar_SCP.SCPStatement10_pledges_t10_confirm_t6__initZ in systemtest-simple.o
  "scpd.types.Stellar_SCP.SCPStatement10_pledges_t10_prepare_t11__xopEqualsFKxSQDbQCzQCwQCmQCbQBsKxQvZb", referenced from:
      __D72TypeInfo_S4scpd.types.Stellar_SCP.SCPStatement10_pledges_t10_prepare_t6__initZ in systemtest-simple.o
  "scpd.types.Stellar_SCP.SCPStatement10_pledges_t10_prepare_t9__xtoHashFNbNeKxSQDcQDaQCxQCnQCcQBtZm", referenced from:
      __D72TypeInfo_S4scpd.types.Stellar_SCP.SCPStatement10_pledges_t10_prepare_t6__initZ in systemtest-simple.o
  "scpd.types.Stellar_SCP.SCPStatement10_pledges_t14_externalize_t11__xopEqualsFKxSQDfQDdQDaQCqQCfQBwKxQvZb", referenced from:
      __D76TypeInfo_S4scpd.types.Stellar_SCP.SCPStatement10_pledges_t14_externalize_t6__initZ in systemtest-simple.o
  "scpd.types.Stellar_SCP.SCPStatement10_pledges_t14_externalize_t9__xtoHashFNbNeKxSQDgQDeQDbQCrQCgQBxZm", referenced from:
      __D76TypeInfo_S4scpd.types.Stellar_SCP.SCPStatement10_pledges_t14_externalize_t6__initZ in systemtest-simple.o
  "scpd.types.Stellar_SCP.SCPStatement10_pledges_t8toStringMxFNeZAya", referenced from:
      __D60TypeInfo_S4scpd.types.Stellar_SCP.SCPStatement10_pledges_t6__initZ in systemtest-simple.o
  "scpd.types.Stellar_SCP.SCPStatement11__xopEqualsFKxSQCdQCbQByQBoKxQpZb", referenced from:
      8TypeInfo_S4scpd.types.Stellar_SCP.SCPStatement6__initZ in systemtest-simple.o
  "scpd.types.Stellar_SCP.SCPStatement9__xtoHashFNbNeKxSQCeQCcQBzQBpZm", referenced from:
      8TypeInfo_S4scpd.types.Stellar_SCP.SCPStatement6__initZ in systemtest-simple.o
  "scpd.types.Stellar_SCP.__ModuleInfoZ", referenced from:
      agora.common.Config12__ModuleInfoZ in systemtest-simple.o
      agora.utils.PrettyPrinter.__ModuleInfoZ in systemtest-simple.o
  "scpd.types.Stellar_SCP13SCPNomination11__xopEqualsFKxSQCeQCcQBzQBpKxQpZb", referenced from:
      9TypeInfo_S4scpd.types.Stellar_SCP13SCPNomination6__initZ in systemtest-simple.o
  "scpd.types.Stellar_SCP13SCPNomination9__xtoHashFNbNeKxSQCfQCdQCaQBqZm", referenced from:
      9TypeInfo_S4scpd.types.Stellar_SCP13SCPNomination6__initZ in systemtest-simple.o
  "scpd.types.Stellar_SCP9SCPBallot11__xopEqualsFKxSQBzQBxQBuQBkKxQpZb", referenced from:
      4TypeInfo_S4scpd.types.Stellar_SCP9SCPBallot6__initZ in systemtest-simple.o
  "scpd.types.Stellar_SCP9SCPBallot9__xtoHashFNbNeKxSQCaQByQBvQBlZm", referenced from:
      4TypeInfo_S4scpd.types.Stellar_SCP9SCPBallot6__initZ in systemtest-simple.o
  "scpd.types.Stellar_types12__ModuleInfoZ", referenced from:
      agora.common.Config12__ModuleInfoZ in systemtest-simple.o
      agora.utils.PrettyPrinter.__ModuleInfoZ in systemtest-simple.o
  "scpd.types.Stellar_types.PublicKey11__xopEqualsFKxSQCbQBzQBwQBkKxQpZb", referenced from:
      6TypeInfo_S4scpd.types.Stellar_types.PublicKey6__initZ in systemtest-simple.o
  "scpd.types.Stellar_types.PublicKey6__ctorMFNaNbNcNiNfSQCeQCc7XDRBase__T12opaque_arrayVki32ZQuZSQDtQDrQDoQDc", referenced from:
      agora.common.Config.toSCPQuorumSetFxSQBnQBkQBg12QuorumConfigZS4scpd.types.Stellar_SCP.SCPQuorumSet in systemtest-simple.o
  "scpd.types.Stellar_types.PublicKey9__xtoHashFNbNeKxSQCcQCaQBxQBlZm", referenced from:
      6TypeInfo_S4scpd.types.Stellar_types.PublicKey6__initZ in systemtest-simple.o
  "scpd.types5Utils12__ModuleInfoZ", referenced from:
      agora.common.Config12__ModuleInfoZ in systemtest-simple.o
  "scpd.types.XDRBase__T12opaque_arrayVki32ZQu8__mixin26__ctorMFNaNbNcNiNfMxAhbZSQDbQCzQCw__TQCrVki32ZQDa", referenced from:
      agora.common.Config.toSCPQuorumSetFxSQBnQBkQBg12QuorumConfigZS4scpd.types.Stellar_SCP.SCPQuorumSet in systemtest-simple.o
  "agora.common10BanManager12__ModuleInfoZ", referenced from:
      agora.common.Config12__ModuleInfoZ in systemtest-simple.o
  "agora.common10BanManagerQm6Config6__initZ", referenced from:
      4TypeInfo_S5agora.common10BanManagerQm6Config6__initZ in systemtest-simple.o
      agora.common.Config21parseBanManagerConfigFPS5dyaml4node4NodeKxSQCnQCkQCg11CommandLineZSQDlQDi10BanManagerQmQDs in systemtest-simple.o
  "agora9consensus4data13ConsensusData12__ModuleInfoZ", referenced from:
      agora.utils.PrettyPrinter.__ModuleInfoZ in systemtest-simple.o
  "agora9consensus4data13ConsensusDataQp11__xopEqualsFKxSQCdQCaQBtQBrQBuKxQsZb", referenced from:
      8TypeInfo_S5agora9consensus4data13ConsensusDataQp6__initZ in systemtest-simple.o
  "agora9consensus4data13ConsensusDataQp9__xtoHashFNbNeKxSQCeQCbQBuQBsQBvZm", referenced from:
      8TypeInfo_S5agora9consensus4data13ConsensusDataQp6__initZ in systemtest-simple.o
  "void push_back<stellar::SCPQuorumSet, xdr::xvector<stellar::SCPQuorumSet, 4294967292u> >(xdr::xvector<stellar::SCPQuorumSet, 4294967292u>&, stellar::SCPQuorumSet&)", referenced from:
      agora.common.Config.toSCPQuorumSetFxSQBnQBkQBg12QuorumConfigZS4scpd.types.Stellar_SCP.SCPQuorumSet in systemtest-simple.o
  "void push_back<stellar::PublicKey, xdr::xvector<stellar::PublicKey, 4294967292u> >(xdr::xvector<stellar::PublicKey, 4294967292u>&, stellar::PublicKey&)", referenced from:
      agora.common.Config.toSCPQuorumSetFxSQBnQBkQBg12QuorumConfigZS4scpd.types.Stellar_SCP.SCPQuorumSet in systemtest-simple.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
**So, I could easily find a module that needed to be added.
And I committed the final result.**

**Comment by Geod24** [comment]
I see, so it's a PR to support #637 . I still don't see how this solves #578 . #578 is an error which happens on v0.x.x *already*.

**Comment by MichaelKim20** [comment]
The System Integration Test must not be dependent on the SCP module.
Therefore, I will close this PR.

**Pull request closed without merging**
