### PR TITLE
Add code coverage

### PR DESCRIPTION
**Pull request by Geod24**

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
What do all these rectangles represent?

**Comment by AndrejMitrovic** [comment]
Ok to merge this? I can ignore the random segfault.

**Comment by Geod24** [comment]
> What do all these rectangles represent?

https://docs.codecov.io/docs/graphs

**Comment by Geod24** [comment]
💚

**Review by AndrejMitrovic — APPROVED** [review]

**Pull request merged**
