### PR TITLE
Another set of CircleCI fixes

### PR DESCRIPTION
**Pull request by AndrejMitrovic**

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
Unfortunately it still doesn't resolve the issue. But debugging continues..

**Comment by AndrejMitrovic** [comment]
> node-2_1_2504f5c08725 | 2020-08-23 14:44:10,379 Info [agora.network.NetworkManager] - Found new Validator: http://node-7:7826 (key: GDNODE7J5EUK7T6HLEO2FDUBWZEXVXHJO7C4AF5VZAKZENGQ4WR3IX2U)core.exception.AssertError@submodules/eventcore/source/eventcore/drivers/posix/dns.d(76): Assertion failure

Hmm this assert still fails sometimes..

**Comment by Geod24** [comment]
Also this:

```
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.638919694Z Warning (thread: main): leaking eventcore driver because there are still active handles
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.638924687Z    FD 10 (streamListen)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.638929101Z    FD 12 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.638933411Z    FD 13 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.638937809Z    FD 14 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.638942036Z    FD 15 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.638946347Z    FD 16 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.638951363Z    FD 17 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.638955579Z    FD 18 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.638959669Z    FD 19 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.638980753Z    FD 20 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.638985588Z    FD 21 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.638989727Z    FD 22 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.638993792Z    FD 23 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.638997937Z    FD 24 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639001990Z    FD 25 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639006007Z    FD 26 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639010869Z    FD 27 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639015242Z    FD 28 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639019546Z    FD 29 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639023989Z    FD 30 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639028130Z    FD 31 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639032640Z    FD 32 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639036978Z    FD 33 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639041578Z    FD 34 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639067064Z    FD 35 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639072500Z    FD 36 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639076984Z    FD 37 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639081561Z    FD 38 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639086015Z    FD 39 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639090539Z    FD 40 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639094719Z    FD 41 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639105485Z    FD 42 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639109921Z    FD 43 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639114316Z    FD 44 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639118739Z    FD 46 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639123226Z    FD 47 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639127643Z    FD 48 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639150530Z    FD 49 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639154919Z    FD 50 (streamSocket)
node-7_1_3e996a01b79d | 2020-08-23T14:44:18.639159332Z    FD 53 (streamSocket)
```

**Comment by AndrejMitrovic** [comment]
Yep. I think I saw this being reported upstream already though.

**Comment by Geod24** [comment]
Still draft ?

**Comment by AndrejMitrovic** [comment]
All of these were folded into other PRs, so I will just close it.

Also while I was experimenting with this PR this is where I initially found the issue with the DNS.

By the way I'm hoping https://github.com/vibe-d/eventcore/pull/153 will finally get it resolved.

**Pull request closed without merging**
