### PR TITLE
Flash: Bound re-try loops in update and payment proposals

### PR DESCRIPTION
**Pull request by omerfirmak**

### CODE REVIEW

**Review by AndrejMitrovic — APPROVED** [review]

**Comment by AndrejMitrovic** [comment]
The integration test seems to be failing consistently. But it shouldn't, it doesn't use the flash layer.

Edit: seems other PRs are failing too.

**Comment by hewison-chris** [comment]
> The integration test seems to be failing consistently. But it shouldn't, it doesn't use the flash layer.
> 
> Edit: seems other PRs are failing too.

You will need to rebase from upstream.

**Comment by hewison-chris** [comment]
> > The integration test seems to be failing consistently. But it shouldn't, it doesn't use the flash layer.
> > Edit: seems other PRs are failing too.
> 
> You will need to rebase from upstream.

Although maybe we have a new problem:-
`Check condition failed after timeout of 1 minute and 600 attempts: >>CI: node-0 has not completed discovery after 1 minute.`

**Comment by omerfirmak** [comment]
Rebased

**Comment by omerfirmak** [comment]
All green

**Pull request merged**
