### PR TITLE
Move PreImage utilities into a common module

### PR DESCRIPTION
**Pull request by Geod24**
This way they can be re-used when a node is simulating another node,
or want to do speculative work.

### CODE REVIEW

**Review by linked0 — APPROVED** [review]
LGTM

**Comment by Geod24** [comment]
Should be fixed now

**Comment by linked0** [comment]
> Should be fixed now

Do you mean "merge at green"?

**Comment by Geod24** [comment]
Related to #907 as we need to add pre-images to the genesis block as part of the Enrollment.

**Pull request merged**
