### PR TITLE
Revert "Move isValidEnrollment unittest into validation"

### PR DESCRIPTION
**Pull request by TrustHenry**
Reverts bpfkorea/agora#472

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
We're reverting the change because of cyclic imports.

It looks like this code tests both the `EnrollmentManager.createEnrollment` **and** the validation with `isValidEnrollment`. 

However, Ideally we would have two unittests. One in `EnrollmentManager.d` that just tests that `createEnrollment` always creates a valid enrollment. And then **another** unittest inside of `Validation.d` which tests various valid **and** invalid Enrollment structures.

**Comment by Geod24** [comment]
Can we just split it then ?

**Comment by AndrejMitrovic** [comment]
Hmm actually the test is missing checks. `createEnrollment` returns a boolean but it was not tested in these unittests..

**Comment by TrustHenry** [comment]
The return bool test of createEnrollment can be added in other PRs.

**Comment by TrustHenry** [comment]
`CreationEnrollment` and `isValidEnrollment` tests cannot be divided. CreateEnrollment is required for testing `isValidEnrollment`.

**Comment by AndrejMitrovic** [comment]
> The return bool test of createEnrollment can be added in other PRs.

Yes. As this is blocking other people's work.

> CreateEnrollment is required for testing isValidEnrollment.

`isValidEnrollment` should be tested with both valid and invalid Enrollment structures. Those can be created manually.

**Pull request merged**
