### PR TITLE
FullNode / Validator cleanups and consistency improvements

### PR DESCRIPTION
**Pull request by Geod24**
Part of #1885 but took them out to speed up review.

### CODE REVIEW

**Comment by linked0** [comment]
Need to change the first commit's message.

**Review by hewison-chris — APPROVED** [review]
LGTM, just maybe correct the commit message for rename get -> make

**Review by linked0 — APPROVED** [review]

**Comment by Geod24** [comment]
Fixed the two typos in the first commit.

**Review by kchulj — APPROVED** [review]
LGTM

**Comment by ferencdg** [comment]
now that we no longer have get... when it should be make..., can we also change: getAlreadyCreatedBanManager -> getBanManager() ?

**Comment by Geod24** [comment]
You know what, that was one of the point of doing this change, and then I forgot 🤦 
I suggest to see if the CI is happy with this run, merge if it is, and I'll submit a follow up PR. If it's not happy, I'm just going to amend and re-trigger, if that works for you ?

**Review by ferencdg — APPROVED** [review]

**Comment by Geod24** [comment]
The CI has spoken. Or rather timed out. So I added the change.

**Pull request merged**
