### PR TITLE
Use the new unittest helper routine

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
So this is the missing part, because one PR got rebased before the other.

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
However, I am very unsure about importing into the `test` package in here.. so maybe the routines should be moved somewhere else.

**Comment by AndrejMitrovic** [comment]
Update: Moved helper functionality into their proper location.

**Comment by Geod24** [comment]
Arg... This is an interesting conundrum. Those functions should IMO not be used in production. Let's discuss on Monday.

**Comment by AndrejMitrovic** [comment]
So `getChainedBlocks` was removed. `getChainedTransactions` was moved, but I now versioned it into `version(unittest)`, this should ensure it's never used in production. Is this still ok?

**Comment by AndrejMitrovic** [comment]
Rebased. W.r.t. "rule of three", this function is already used in the networking tests, now it's also being used here.

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
