### PR TITLE
Refactor some code

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
Split off from https://github.com/bpfkorea/agora/pull/113

There's more to do. I had to leave out the assertion in `makeBlock` until a subsequent PR.

### CODE REVIEW

**Review by Geod24 — APPROVED** [review]

**Comment by Geod24** [comment]
Last commit is not really atomic but I'll allow it

**Comment by Geod24** [comment]
> source/agora/common/Block.d(246,33): Error: undefined identifier getGenesisKeyPair

**Comment by AndrejMitrovic** [comment]
Because of styling issues?

**Comment by AndrejMitrovic** [comment]
Fixed and re-atomized the commits.

**Pull request merged**
