### PR TITLE
Change the CI so it tests compiler-master on merge

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
I will see if I can get rid of duplication. This is a test for now.

#485

### CODE REVIEW

**Comment by Geod24** [comment]
If you want to reduce deduplication you could look into YAML anchors.

**Comment by Geod24** [comment]
Can we give a shot at re-enabling ldc as well ?

**Comment by AndrejMitrovic** [comment]
The last commit didn't work. Trying out the one before it.

**Comment by AndrejMitrovic** [comment]
It seems the CI doesn't react to any commit changes in this PR anymore. I'll have to open a new one..

**Comment by Geod24** [comment]
Sometimes it's enough to close/reopen BTW.

**Comment by AndrejMitrovic** [comment]
It would help if they had some kind of console/log.

**Pull request closed without merging**
