### PR TITLE
Flash: Fix initial channel state and some faulty tests

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
This particular test seems to fail somewhat frequently.

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
This finally revealed the two different errors we're getting:

> core.exception.AssertError@source/agora/test/Flash.d(1001): Couldn't pay invoice: PathNotFound
> core.exception.AssertError@source/agora/test/Flash.d(1345): Rejected

In one a payment path is not found, which probably means a channel update wasn't received (or we haven't waited for it long enough). The other rejects the creation of a second channel towards a peer.

**Comment by AndrejMitrovic** [comment]
I think I see the issue. We're waiting via `waitForChannelDiscovery` but not via `waitForChannelUpdate`. The payment path finder won't find any paths unless a ChannelUpdate was received. So we need to add these calls.

**Comment by AndrejMitrovic** [comment]
And the failure in line 1345 is because the ChannelState's first enum value is Rejected. It just means the channel was just initialiazed. So I'll fix this by adding another state to it.

**Comment by AndrejMitrovic** [comment]
> And the failure in line 1345 is because the ChannelState's first enum value is Rejected. It just means the channel was just initialiazed. So I'll fix this by adding another state to it.

Actually never mind. It was because there was another missing wait call. However adding another state will help anyways.

**Comment by AndrejMitrovic** [comment]
I added a couple of commits to fix the test failures. I'm gonna run the CI half a dozen times just to confirm the bug doesn't reappear.

**Comment by AndrejMitrovic** [comment]
Added another bugfix! Channel updates weren't gossipped after establishing connection.

**Comment by AndrejMitrovic** [comment]
```
/home/runner/work/agora/agora/source/scpp/lib/xdrpp/xdrpp/message.h:66:1: error: static_assert failed due to requirement 'std::is_standard_layout<xdr::message_t>::value' "message_t should be standard layout"
static_assert(std::is_standard_layout<message_t>::value,
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

This looks like suddenly the C++ compiler was updated?

**Comment by AndrejMitrovic** [comment]
```
2021-05-14T08:05:03.5732032Z 2021-05-14 08:04:53,502 [32mInfo[0m [agora.flash.Node] - gossipChannelUpdates() added channel update: { chan_id: 0x821c84fff11fe9ac9258c573ed205f38d3cded975f76d012ef88b493a6a808157b413a53d7f0b402badf0f3077f828f86bd6c23c8eac181b16ae340264cab4f6, direction: PaymentDirection.TowardsPeer, fixed_fee: 1, proportional_fee: 1, htlc_delta: 1, update_idx: 0, sig: 0x28269246cbe48fbe889ce35f9556980c44d38658afbe0d70034ea9ec61b8fa510ab753aec9502ac939a375362aeca580bd49c15383bd9713db08689f47790e7d }. chan_id: 0x821c84fff11fe9ac9258c573ed205f38d3cded975f76d012ef88b493a6a808157b413a53d7f0b402badf0f3077f828f86bd6c23c8eac181b16ae340264cab4f6. direction: PaymentDirection.TowardsPeer. address: 0X00007F29BB330808

2021-05-14T08:05:03.5742135Z 2021-05-14 08:04:53,511 [32mInfo[0m [agora.flash.Node] - Can't find chan ID 0x829613e8211938938d2d8458764922cb26b5f0892c811e623344c1e5bc223c8b04061910f8e08d413e712321dd821c2110c5b08c9e0c5e0b467502235893e765. map: 0X00007F29BB330808
```

How is this even possible? An item is added to a map, and then it just vanishes. Memory corruption?

**Comment by omerfirmak** [comment]
> ```
> 2021-05-14T08:05:03.5732032Z 2021-05-14 08:04:53,502 �[32mInfo�[0m [agora.flash.Node] - gossipChannelUpdates() added channel update: { chan_id: 0x821c84fff11fe9ac9258c573ed205f38d3cded975f76d012ef88b493a6a808157b413a53d7f0b402badf0f3077f828f86bd6c23c8eac181b16ae340264cab4f6, direction: PaymentDirection.TowardsPeer, fixed_fee: 1, proportional_fee: 1, htlc_delta: 1, update_idx: 0, sig: 0x28269246cbe48fbe889ce35f9556980c44d38658afbe0d70034ea9ec61b8fa510ab753aec9502ac939a375362aeca580bd49c15383bd9713db08689f47790e7d }. chan_id: 0x821c84fff11fe9ac9258c573ed205f38d3cded975f76d012ef88b493a6a808157b413a53d7f0b402badf0f3077f828f86bd6c23c8eac181b16ae340264cab4f6. direction: PaymentDirection.TowardsPeer. address: 0X00007F29BB330808
> 
> 2021-05-14T08:05:03.5742135Z 2021-05-14 08:04:53,511 �[32mInfo�[0m [agora.flash.Node] - Can't find chan ID 0x829613e8211938938d2d8458764922cb26b5f0892c811e623344c1e5bc223c8b04061910f8e08d413e712321dd821c2110c5b08c9e0c5e0b467502235893e765. map: 0X00007F29BB330808
> ```
> 
> How is this even possible? An item is added to a map, and then it just vanishes. Memory corruption?

They are not the same chan_id?
0x821c84fff11fe9ac9258c573ed205f38d3cded975f76d012ef88b493a6a808157b413a53d7f0b402badf0f3077f828f86bd6c23c8ea
0x829613e8211938938d2d8458764922cb26b5f0892c811e623344c1e5bc223c8b04061910f8e08d413e712321dd821c2110c5b0

**Comment by Geod24** [comment]
@omerfirmak : Could you go through the diff and check what should be integrated into HEAD ?

**Pull request closed without merging**
