### PR TITLE
Switch dependencies from dub fetch to git submodules

### PR DESCRIPTION
**Pull request by Geod24**
Same version, same code, but it should be easier to deal with and more predictable

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
Yay, it's green.

**Review by MichaelKim20 — APPROVED** [review]

**Comment by Geod24** [comment]
This is ready to go

**Comment by AndrejMitrovic** [comment]
So if I have any build scripts of my own, I have to make sure to use `--skip-registry=all` always?

**Review by AndrejMitrovic — APPROVED** [review]

**Comment by Geod24** [comment]
No

**Pull request merged**
