### PR TITLE
Fix SCPEnvelope serialization to produce valid JSON

### PR DESCRIPTION
**Pull request by Geod24**
Before it was producing a weird JSON hybrid that was not parseable
by anything but the fromString method.

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
LGTM. `(*obj)` can just be `obj` when accessing properties, but I guess you left it on purpose?

**Review by AndrejMitrovic — APPROVED** [review]

**Comment by Geod24** [comment]
`deserializeJson` is not a property, it's using UFCS. Currently it accepts a `Json` so it would work, but I'm a bit wary of templates (as soon as you have templates, the auto-dereferencing just falls appart).

**Comment by TrustHenry** [comment]
Github actions CI can't check ??

**Comment by Geod24** [comment]
Yeah IDK why it didn't show up. Rebased and now it's there.

**Pull request merged**
