### PR TITLE
Fix default compiler setting

### PR DESCRIPTION
**Pull request by AndrejMitrovic**

### CODE REVIEW

**Comment by Geod24** [comment]
Should we raise a bug upstream ?

**Comment by AndrejMitrovic** [comment]
Always.

**Review by Geod24 — APPROVED** [review]

**Comment by AndrejMitrovic** [comment]
https://github.com/dlang/dub/issues/1918

**Comment by AndrejMitrovic** [comment]
@Geod24 auto-merge didn't work, it seems.

**Pull request merged**
