### PR TITLE
Add config.node parameter in Ledger Constructor

### PR DESCRIPTION
**Pull request by TrustHenry**
We need to use config.node in Ledger.
In order to make a block, it is necessary to read the publickey and seed of a node, and to check whether the node is intended to be a validator.
issue #205

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
> We need to use config.node in Ledger.

The commit message should say why it's necessary, just like the pull request comment.

**Comment by AndrejMitrovic** [comment]
Then I'll merge. :)

**Comment by TrustHenry** [comment]
> The commit message should say why it's necessary, just like the pull request comment.

add commit message. :)

**Review by AndrejMitrovic — APPROVED** [review]

**Comment by TrustHenry** [comment]
It's green.

**Pull request merged**
