### PR TITLE
DNS: Fix domain name decompression and better RDATA toString

### PR DESCRIPTION
**Pull request by omerfirmak**

### CODE REVIEW

**Comment by Geod24** [comment]
Do we need the second commit ? It looks like a lot of changes for a marginal gain.

**Comment by Geod24** [comment]
And if you want to fix `toString`, do it at the RR level, where you know the type, instead of duplicating it.

**Comment by omerfirmak** [comment]
> Do we need the second commit ? It looks like a lot of changes for a marginal gain.

The output was incorrect, it would print "1 bytes" for an IPv4 addr

> And if you want to fix toString, do it at the RR level, where you know the type, instead of duplicating it.

But then you would have to manually print other fields as well, no?

**Comment by Geod24** [comment]
> But then you would have to manually print other fields as well, no?

Yeah but that's not really a big deal is it ?

**Comment by omerfirmak** [comment]
> Do we need the second commit

Dropped

**Review by Geod24 — APPROVED** [review]
Can you add a test ?

**Pull request merged**
