### PR TITLE
Make block catchup interval configurable

### LINKED ISSUE #1478: Make block catchup interval configurable
Currently Agora nodes try to catchup to other nodes and request the known blocks from them in every 2 seconds. This is too low and also should be configurable.

### PR DESCRIPTION
**Pull request by ferencdg**
fixes: #1478

### CODE REVIEW

**Review by Geod24 — APPROVED** [review]

**Review by kchulj — APPROVED** [review]

**Comment by Geod24** [comment]
Actually, can you make it low in`test/Base.d` ?

**Comment by ferencdg** [comment]
should be fixed by now

**Review by Geod24 — APPROVED** [review]

**Comment by Geod24** [comment]
The CircleCI failure is legit

**Comment by ferencdg** [comment]
> The CircleCI failure is legit

decreased the catchup duration, should pass now

**Review by AndrejMitrovic — APPROVED** [review]

**Pull request merged**
