### PR TITLE
Test: Relax assertions in ValidatorRecurringEnrollment

### PR DESCRIPTION
**Pull request by omerfirmak**
to hopefully make it less flakey.

### CODE REVIEW

**Comment by Geod24** [comment]
So, some enrollments are not making it to the blocks and the validator is not enrolled for one or more block ?

**Comment by omerfirmak** [comment]
> 
> 
> So, some enrollments are not making it to the blocks and the validator is not enrolled for one or more block ?

Yep, it tests gaps in enrollment essentially.

**Comment by Geod24** [comment]
Any way we can wait for enrollment propagation instead of working around it ? Similar to how we do it with TXs.

**Comment by omerfirmak** [comment]
> 
> 
> Any way we can wait for enrollment propagation instead of working around it ? Similar to how we do it with TXs.

I wouldnt say this is a workaround. This can happen in a real life scenario and what those assertions test still fully verifies our intented behaviour. Waiting for propagation sounds more like a workaround IMHO.

**Review by hewison-chris — APPROVED** [review]
LGTM

**Review by kchulj — APPROVED** [review]
LGTM

**Review by Geod24 — APPROVED** [review]
Fair enough

**Pull request merged**
