### PR TITLE
Config fixes: Special case 'root' name & pass a YAML `Node` to `Converter`

### PR DESCRIPTION
**Pull request by Geod24**
See the rationale in each commit.

### CODE REVIEW

**Comment by Geod24** [comment]
Note that those two commits were created while working on two unrelated piece of work, but since they are both config-related, and trivial, I put them in the same PR to save CI time. LMK if anyone prefer to have them split.

**Comment by kchulj** [comment]
I think same PR is ok since they are both related to `Config`.

**Comment by kchulj** [comment]
Is the CI failure legit..?

**Comment by Geod24** [comment]
Given that both failures are in Flash, I doubt so. The third one is a timeout, and one of the 4 passed. So I re-ran it.

**Review by linked0 — APPROVED** [review]

**Review by kchulj — APPROVED** [review]

**Pull request merged**
