### PR TITLE
Minor improvements to SQL usability

### PR DESCRIPTION
**Pull request by Geod24**
Shortening names so join and manual queries are easier, and using TEXT so that the DB is (a bit) more readable.
Also having the `pubkey_hash` field as TEXT will allow to join `utxo` with `validator`.

### CODE REVIEW

**Comment by ferencdg** [comment]
I see a lot of mixing up of `pubkey_hash` and `pubkey` in our code like this
image

seems we store the pubkey, but keep refering to it as pubkey_hash... I wonder if we could clean up all those too

**Comment by Geod24** [comment]
Correct, and renaming those parameter is planned, but the priority would be to have `val` be correctly serialized instead of a blob.
See https://github.com/bosagora/agora/blob/v0.x.x/doc/Database.md#state-db where this is mentioned.

**Comment by Geod24** [comment]
Added a commit to rename `pubkey_hash`

**Review by hewison-chris — APPROVED** [review]
LGTM

**Pull request merged**
