### PR TITLE
Tests: Unify network registries into a single one

### PR DESCRIPTION
**Pull request by Geod24**
How I feel about the typed registry idea:

To say the least

### CODE REVIEW

**Comment by Geod24** [comment]
Depends on: https://github.com/Geod24/localrest/pull/128

**Comment by Geod24** [comment]
Dependent PR has been merged, rebased.

**Review by hewison-chris — APPROVED** [review]
LGTM

**Comment by linked0** [comment]
LGTM

**Review by kchulj — APPROVED** [review]
LGTM

**Pull request merged**
