### PR TITLE
Fix race condition in the Ledger test

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
See commit description.

### CODE REVIEW

**Comment by Geod24** [comment]
Well, to be fair, the node should support this...

**Comment by AndrejMitrovic** [comment]
> Well, to be fair, the node should support this...

Adding tx's to the pool when they reference unknown utxos?

**Comment by Geod24** [comment]
To some extent, I'd say yes. But since we can't really rely on it right now, let's go with this.

**Review by Geod24 — APPROVED** [review]
Merge at will

**Comment by AndrejMitrovic** [comment]
I think we should file an issue for this. I can see us allowing tx's referencing UTXOs if they're at least partially valid. We could add a cleanup routine which periodically cleans up old transactions in the pool, to avoid DDoS.

**Pull request merged**
