### PR TITLE
Limit `Address` type to only accept schemes supported by Agora

### LINKED ISSUE #2882: Expected Address schema should be limited
Currently we can even have addresses starting with `ftp`, this will cause problems with the addition of the `URI` records #2869  for the registry. We should only expect addresses with schemes among `http`, `https` and `agora` within Agora.

### PR DESCRIPTION
**Pull request by mkykadir**
Fixes #2882 

Let's see if we have invalid scheme usages in tests first

### CODE REVIEW

**Review by Geod24 — CHANGES_REQUESTED** [review]
Need to swap both commits otherwise test won't pass on the first commit. Then feel free to self-merge.

**Comment by Geod24** [comment]
Also this means we still accept `dns://` addresses for non-DNS situation (e.g. `network:`).

**Comment by mkykadir** [comment]
> Also this means we still accept `dns://` addresses for non-DNS situation (e.g. `network:`).

Those can be validated through `Config`

**Comment by mkykadir** [comment]
> Need to swap both commits otherwise test won't pass on the first commit. Then feel free to self-merge.

Swapped

**Comment by omerfirmak** [comment]
We can lose the `tcp` from here as well then

https://github.com/omerfirmak/agora/commit/d9c2b82cb018d20e0f080f39d21627d908649883

**Review by omerfirmak — APPROVED** [review]
Still needs @Geod24 to approve

**Review by linked0 — APPROVED** [review]
LGTM

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
