### PR TITLE
Fix memory corruption when the ballot timer would wake up

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
Split from https://github.com/bpfkorea/agora/pull/974

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
omg I hate Windows

**Comment by AndrejMitrovic** [comment]
ah I guess I'm running into https://issues.dlang.org/show_bug.cgi?id=20805 again.

**Comment by AndrejMitrovic** [comment]
Ok hopefully fixed now. If not I'll fix again later.

**Review by Geod24 — APPROVED** [review]
Should we just remove `toVec` ?

**Comment by AndrejMitrovic** [comment]
> Should we just remove toVec ?

Yeeeep.

**Comment by AndrejMitrovic** [comment]
https://github.com/bpfkorea/agora/issues/723

**Comment by AndrejMitrovic** [comment]
I filed that bug and totally forgot about it, it seems.

**Pull request merged**
