### PR TITLE
Refactor UTXO related modules

### LINKED ISSUE #1775: confusing module/class names UTXODB, UTXOSET
currently
UTXOSet.d has one class called UTXOCache
UTXODB.d has one class called UTXOSet
:eyes:

### PR DESCRIPTION
**Pull request by kchulj**
As @ferencdg mentioned, `UTXOSet.d` had a class called `UTXOCache` and `UTXODB.d` had one class called `UTXOSet`. This is confusing, so the files in `agora.consensus.state` have been renamed and refactored.

Each file now contains the module/class with the respective name:

- `UTXOCache.d`: Base class for a UTXO set. Includes `TestUTXOSet` which is an AA-backed UTXO set.
- `UTXODB.d`: `ManagedDatabase` of UTXOs using SQLite as the backing store. It is only imported by `UTXOSet`.
- `UTXOSet.d`: Now has its own module. Contains a SQLite-backed UTXO set `class`. This is used the most.

Please see each commit for the details. They will be squashed after.

Fixes #1775

### CODE REVIEW

**Comment by ferencdg** [comment]
I saw some import re-ordering(the original order was not alphabetical) that could have gone into a separate commit, but LGTM

**Comment by kchulj** [comment]
> I saw some import re-ordering(the original order was not alphabetical) that could have gone into a separate commit, but LGTM

Right. I have seen these re-orderings, both in same and separate commits 🤔

**Review by linked0 — APPROVED** [review]
LGTM

**Review by ferencdg — APPROVED** [review]

**Comment by kchulj** [comment]
Thank you for the reviews. Will wait for @Geod24 final review and squash.

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
