### PR TITLE
Optimize `NetworkManager.discover` memory usage

### PR DESCRIPTION
**Pull request by Geod24**
It doesn't really fix the design issues, but at least it should reduce memory usage quite a bit.

### CODE REVIEW

**Review by omerfirmak — APPROVED** [review]

**Comment by Geod24** [comment]
The CI really doesn't like this one.

**Comment by omerfirmak** [comment]
Will merge if we get a green CI

**Comment by Geod24** [comment]
I re-ran it a dozen time, the failures are legit, but I don't yet know why.

**Comment by Geod24** [comment]
Done in other PRs.

**Pull request closed without merging**
