### PR TITLE
vibe-core: v1.14.0 to v1.16.0

### PR DESCRIPTION
**Pull request by Geod24**
This includes an update to the logging system which will make our production
trace logs much less verbose.

### CODE REVIEW

**Review by kchulj — APPROVED** [review]
There is an error in `Change permission on lst files` of integration but I don't think it is related.

**Comment by Geod24** [comment]
I think it is. I'll track down the underlying bug and will report it.

**Comment by AndrejMitrovic** [comment]
> sudo: unable to execute /usr/bin/chmod: Argument list too long

Super weird error. Should we just retry?

**Comment by Geod24** [comment]
I added a workaround for the issue. It does add 30s to the runtime of the CI, but it works. And opened #1868.

**Pull request merged**
