### PR TITLE
SCP: Simplify PublicKey, use simple uint256

### PR DESCRIPTION
**Pull request by Geod24**
I tested again, this passes just fine on my machine, so let's give it another try.

### CODE REVIEW

**Comment by Geod24** [comment]
Actually updated the quorum hashes as well, it wasn't that much.

**Comment by Geod24** [comment]
> Actually updated the quorum hashes as well, it wasn't that much.

Forgot a bunch of them, fixed now.

**Comment by Geod24** [comment]
💚

**Review by linked0 — APPROVED** [review]
LGTM

**Review by hewison-chris — APPROVED** [review]
LGTM

**Pull request merged**
