### PR TITLE
Fix 745 - Upload build artifacts

### PR DESCRIPTION
**Pull request by Geod24**

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
How do we retrieve the artifacts once they're uploaded?

**Comment by Geod24** [comment]
Why would you do that ?

**Comment by Geod24** [comment]
Screen Shot 2020-05-20 at 15 33 40

You click da button

**Comment by AndrejMitrovic** [comment]
documentation generator goes brrrrrrrrr

Is this ready for merge?

**Comment by Geod24** [comment]
Yep

**Review by AndrejMitrovic — APPROVED** [review]

**Pull request merged**
