### PR TITLE
Make the node open its ports before doing discovery()

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
Another small part towards fixing #1117.

### CODE REVIEW

**Comment by Geod24** [comment]
We really need that `schedule` primitive...

**Comment by linked0** [comment]
All the calls in the `node.start()` were also executed asynchronously before through the `Vibe.d`'s timer and asynchronous tasks. Is there a big difference between before and after? The commit message says that this makes the node not to wait for the first discovery round to complete though.

**Comment by AndrejMitrovic** [comment]
I'll rename the commit and change the description.

**Comment by AndrejMitrovic** [comment]
The issue wasn't really about asynchronicity, it was about scheduling.

The `runTask` call would spawn a new fiber and suspend the calling fiber, and the new fiber would spawn many other requests. This starved the first fiber (the one in `main.d` calling `runNode`) - so it only gets to call `listenHTTP` later.

But we want `listenHTTP` to be called right away to make the node available for incoming connections.

Fixed the description.

**Comment by linked0** [comment]
With your explanation, I've just realized that this is about scheduling and just seen the log shown in #1117. Thanks for the detailed explanation.

**Review by linked0 — APPROVED** [review]

**Comment by AndrejMitrovic** [comment]
Thanks. I'll merge it with the approval.

**Pull request merged**
