### PR TITLE
Add the findUTXO feature of the UTXOSet.

### PR DESCRIPTION
**Pull request by TrustHenry**
Currently, the required parameters hash, index are required in the findUTXO in UTXOSet.
In addition, it is necessary to find UTXO setHash directly without index in UTXO pool.

Index is If size_t.max, find the hash parameter by UTXO hash

#205

### CODE REVIEW

**Review by MichaelKim20 — COMMENTED** [review]
All right, I'd like to have the part that uses this.

**Review by MichaelKim20 — APPROVED** [review]

**Comment by AndrejMitrovic** [comment]
Could you add a simple unittest? You could modify one of the existing tests. This is to ensure we don't accidentally break it in the future.

**Comment by TrustHenry** [comment]
added unit test code

**Review by AndrejMitrovic — APPROVED** [review]

**Comment by AndrejMitrovic** [comment]
In general we don not want to make methods public just because they're used in a far away unittest. However I'll merge it for now, because `UtxoSet.d` does not have any unittests of its own. I'll file an issue for this.

**Pull request merged**
