### PR TITLE
Update supported compiler versions: DMD 2.088.0 and LDC 1.17.0

### PR DESCRIPTION
**Pull request by Geod24**

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
The ldc + mac combo seems to consistently fail. I keep re-running it.

**Comment by AndrejMitrovic** [comment]
So far the failures here are consistent, but the stack trace isn't.

**Comment by Geod24** [comment]
Updated

**Comment by Geod24** [comment]
Yay only nightlies + OSX failure

**Review by AndrejMitrovic — APPROVED** [review]

**Pull request merged**
