### PR TITLE
Re-enable OSX, switch to our fork of D-YAML and fix the bug

### PR DESCRIPTION
**Pull request by Geod24**

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
https://travis-ci.com/bpfkorea/agora/jobs/221461723

Well that didn't help.

**Comment by Geod24** [comment]
Yeah I need to do some Python trickery. Will come back to it soon.

**Comment by Geod24** [comment]
Fixed. Upstream PR as https://github.com/dlang-community/D-YAML/pull/247 but for the moment we need the CI back.

**Comment by Geod24** [comment]
💚

**Review by AndrejMitrovic — APPROVED** [review]

**Pull request merged**
