### PR TITLE
Dockerfile: ldc and rdmd are now in community

### PR DESCRIPTION
**Pull request by Geod24**

### CODE REVIEW

**Review by MichaelKim20 — COMMENTED** [review]
I got this message.
apk add dtools-rdmd
ERROR: unsatisfiable constraints:
  dtools-rdmd (missing):
    required by: world[dtools-rdmd]

**Comment by Geod24** [comment]
> I got this message.

What did you do ? Just `docker build .` ?

**Comment by MichaelKim20** [comment]
Sorry, I saw something else, everything is normal.

**Comment by MichaelKim20** [comment]
Removing intermediate container 4b783f2b49b8
 ---> 70a9687ba4e3
Step 7/11 : FROM alpine:edge
 ---> 13d22f83f248
Step 8/11 : RUN apk --no-cache add libexecinfo libgcc libsodium libstdc++ sqlite-libs
 ---> Running in 8e0e6dc03f6c
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
(1/5) Installing libexecinfo (1.1-r1)
(2/5) Installing libgcc (9.2.0-r6)
(3/5) Installing libsodium (1.0.18-r0)
(4/5) Installing libstdc++ (9.2.0-r6)
(5/5) Installing sqlite-libs (3.31.1-r1)
OK: 9 MiB in 19 packages
Removing intermediate container 8e0e6dc03f6c
 ---> 8609207ed343
Step 9/11 : COPY --from=Builder /root/agora/build/agora /usr/local/bin/agora
 ---> 52f475e32f5f
Step 10/11 : WORKDIR /agora/
 ---> Running in f5693b89cc64
Removing intermediate container f5693b89cc64
 ---> f0cd56afdaed
Step 11/11 : ENTRYPOINT [ "/usr/local/bin/agora" ]
 ---> Running in f5cf61c7b09a
Removing intermediate container f5cf61c7b09a
 ---> 84b38ff53721
Successfully built 84b38ff53721
Successfully tagged agora:latest

**Review by MichaelKim20 — APPROVED** [review]
LGTM

**Pull request merged**
