### PR TITLE
[maybe] Add nothrow opApply to BitField

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
@Geod24 actually can we just start using our own fork of Ocean? Since.. well.. everyone at Sociomantic is gone soon?

### CODE REVIEW

**Comment by Geod24** [comment]
> @Geod24 actually can we just start using our own fork of Ocean? Since.. well.. everyone at Sociomantic is gone soon?

I mean, we are already.

**Comment by Geod24** [comment]
@AndrejMitrovic : Why did you need `opApply` ? We have a clean-room implementation now so we can probably close this...

**Comment by AndrejMitrovic** [comment]
Indeed, thanks for killing it.

**Comment by AndrejMitrovic** [comment]
And, it was needed because of a lack of `@safe` and other things in BitArray.

**Pull request closed without merging**
