### PR TITLE
tests: get rid of unused parameter

### PR DESCRIPTION
**Pull request by AndrejMitrovic**

### CODE REVIEW

**Review by omerfirmak — APPROVED** [review]

**Comment by kchulj** [comment]
Would it be possible to get rid of these functions?
I remember they were duplicates of `makeChainedTransactions`.

**Comment by AndrejMitrovic** [comment]
> Would it be possible to get rid of these functions?

That would be ideal. Someone should take care of these in the future.

**Review by kchulj — APPROVED** [review]

**Comment by kchulj** [comment]
> > Would it be possible to get rid of these functions?
> 
> That would be ideal. Someone should take care of these in the future.

Relates #1107

**Comment by AndrejMitrovic** [comment]
Also it's currently blocking my work on the execution engine. I just have this one failing test, but the test was written in such a terrible copy-paste way that it's hard to see what the test is actually trying to accomplish.

**Pull request merged**
