### PR TITLE
Make MemBlockStorage closer to BlockStorage, allow loadAllIndex to throw

### PR DESCRIPTION
**Pull request by Geod24**
Better reviewed commit-by-commit.
As mentioned the two important parts of this PR are the `loadAllIndex` one and the `MemBlockStorage`, which fixes a small issue with the injected dependency diverging in behavior from the actual class.

### CODE REVIEW

**Comment by Geod24** [comment]
Addressed review

**Comment by AndrejMitrovic** [comment]
> Addressed review

```diff
-            // add to index of heigth
+            // add to index of heigtht
```

I think you need some sleep..

**Comment by Geod24** [comment]
Third time's a charm. But also yes.

**Comment by Geod24** [comment]
🍏

**Review by AndrejMitrovic — APPROVED** [review]

**Pull request merged**
