### PR TITLE
Relay TXs only if node has a Validator peer

### LINKED ISSUE #1726: Node should try to gossip transactions after network state is complete
Consider this scenario:

- User boots up their FullNode / Validator
- They have their wallet send a transaction to only their own node
- The node hasn't completed network discovery (maybe it's slow, network is delayed..). Therefore `putTransaction` accepts the tx in the pool but does not gossip it because it has nobody to gossip to.

End result: the tx is now stuck forever in the pool.

If there are incoming transactions which are accepted in the pool but the network state is incomplete then the node should queue these transactions for gossiping later.

### PR DESCRIPTION
**Pull request by omerfirmak**
Fixes #1726

### CODE REVIEW

**Comment by Geod24** [comment]
Doesn't it just push down the issue ? Shouldn't nodes try to periodically sync tx pools instead ?

**Comment by omerfirmak** [comment]
> Doesn't it just push down the issue ? Shouldn't nodes try to periodically sync tx pools instead ?

That may become too costly, no? Especially, when we reach MB levels of tx pool size. Nodes would at least need to share hashes of all the TXs in their pools. What is important is that we share the TXs that are worth externalizing and that is what consensus already does.

My take on this is that tx pools of FullNodes are not important at all. We could probably just make it a Validator thing IMO and FullNodes would only act as relays.

TXs should probably not be valid forever either, they should have an expiration date/block, so that the wallet knows when to retry.

**Comment by omerfirmak** [comment]
I have checked to see if Bitcoin has a mechanism to keep node's mempools in sync and AFAICS there is nothing of the sort.
So we are probably better off with the best effort approach we already have but avoid trying to gossip to an empty set of peers.

**Comment by ferencdg** [comment]
wouldn't it be easier, if the node that is starting up, and haven't finished the network discovery would just not accept the transaction? Wallets should have retry mechanism anyway, no?

**Comment by omerfirmak** [comment]
> 
> 
> wouldn't it be easier, if the node that is starting up, and haven't finished the network discovery would just not accept the transaction? Wallets should have retry mechanism anyway, no?

It may never be able to complete the discovery tho.

**Comment by omerfirmak** [comment]
@Geod24 mentioned the existence of INV messages in BCH. https://www.reddit.com/r/Bitcoincash/comments/jko0ty/bchn_mr_746_merged_faster_transaction_relay/

This makes sense for Bitcoin and its forks as they use PoW but we already do this in the nomination round. So our `Validator` nodes will never suffer from this problem anyways.

Our issue is to somehow get the TX from a `FullNode` to a `Validator` without it ever getting stuck in the `FullNode` forever.

What I think will work is to keep the if check this PR adds and make sure that a `FullNode` always keeps trying to maintain a connection to a `Validator` throughout its lifetime.

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
