### PR TITLE
Flash: Fix spurious test failure

### PR DESCRIPTION
**Pull request by omerfirmak**
This should be addressing the random failure we get occasionally

```
======================================================================

Module tests failed: agora.test.Flash
core.exception.AssertError@source/agora/test/Flash.d(1339): Rejected
----------------
/home/runner/work/agora/agora/source/agora/test/Base.d:162 nothrow void agora.test.Base.testAssertHandler(immutable(char)[], ulong, immutable(char)[]) [0x5584f9e81f15]
exception.d:448 onAssertErrorMsg [0x5584fad84ba7]
exception.d:590 _d_assert_msg [0x5584fad84fd5]
/home/runner/work/agora/agora/source/agora/test/Flash.d:1339 void agora.test.Flash.__unittest_L1208_C1() [0x5584f9e4d0f8]
/home/runner/work/agora/agora/source/agora/test/Flash.d [0x5584f9e63d3e]
/home/runner/work/agora/agora/source/agora/test/Base.d:266 bool agora.test.Base.customModuleUnitTester().runTest(agora.test.Base.customModuleUnitTester().ModTest) [0x5584f9e82eb7]
/home/runner/work/agora/agora/source/agora/test/Base.d:293 core.runtime.UnitTestResult agora.test.Base.customModuleUnitTester() [0x5584f9e81772]
runtime.d:607 runModuleUnitTests [0x5584fad88760]
dmain2.d:551 void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x5584fada2752]
dmain2.d:525 void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5584fada26d2]
dmain2.d:584 _d_run_main2 [0x5584fada2589]
```

### CODE REVIEW

**Comment by Geod24** [comment]
Can you add an explanation on what was wrong ?

**Comment by omerfirmak** [comment]
> Can you add an explanation on what was wrong ?

Added to the commit message, hope that makes sense.

**Comment by Geod24** [comment]
I see a lot of red though, will a rebase help ?

**Comment by omerfirmak** [comment]
> I see a lot of red though, will a rebase help ?

It didnt

**Comment by Geod24** [comment]
~Good news~ HEAD is too

**Comment by Geod24** [comment]
I rebased, but the only failing test seems to point as this being incomplete. Will merge though as it seems to help.

**Comment by omerfirmak** [comment]
> I rebased, but the only failing test seems to point as this being incomplete. Will merge though as it seems to help.

That seems like a different bug.

**Pull request merged**
