### PR TITLE
ValidatorSet: Bypass far preimage check on adding new enrollment

### PR DESCRIPTION
**Pull request by omerfirmak**
If a Validator stays unenrolled more than `ValidatorCycle` amount of
blocks, it would never be able to reveal new preimages after that point.

### CODE REVIEW

**Comment by omerfirmak** [comment]
This is the root cause of our full nodes in production falling behind.

**Review by Geod24 — CHANGES_REQUESTED** [review]
This reverts https://github.com/bosagora/agora/commit/5784d240096667ad0195c7316fa3f5696e64c335

**Comment by omerfirmak** [comment]
> This reverts [5784d24](https://github.com/bosagora/agora/commit/5784d240096667ad0195c7316fa3f5696e64c335)

Updated to also conform to the behaviour https://github.com/bosagora/agora/commit/5784d240096667ad0195c7316fa3f5696e64c335 expects

**Review by hewison-chris — COMMENTED** [review]
Is the title still valid? Also at least one test needs an update as the failure looks related.

**Comment by omerfirmak** [comment]
> Is the title still valid?

Yeah, I think it sill is. We are already checking if commitment is valid while validating the enrollment. There is no reason to use `addPreImage()` and force another validation with far preimage guard.

> Also at least one test needs an update as the failure looks related.

updated, should be good now.

**Comment by omerfirmak** [comment]
Green

**Review by Geod24 — APPROVED** [review]

**Review by hewison-chris — COMMENTED** [review]
LGTM

**Pull request merged**
