### PR TITLE
Re-add system integration tests

### PR DESCRIPTION
**Pull request by Geod24**
```
They were disabled in a previous PR because they were inadvertently broken.
This commit also allows them to be run locally multiple times without manual intervention.
Additionally, they can be re-run without rebuilding the Docker image.
Finally, the output is much more readable now.
```

Lost a lot of time before I could find https://github.com/bpfkorea/agora/issues/312 , which is going to be a big blocker for everyone.

### CODE REVIEW

**Comment by Geod24** [comment]
Goddam it, we're hitting a limitation of CircleCI, where we can't mount volumes.
So yeah, we need #270

**Comment by Geod24** [comment]
Okay I managed to work around the limitation. Let's see if it consistently passes the test.
Now I just need to add coverage export.

**Comment by Geod24** [comment]
Okay, I think we can go ahead with this for the time being, there's much debugging to do on Agora side before I can add code coverage.

**Comment by Geod24** [comment]
Rebased on v0.x.x

**Review by AndrejMitrovic — APPROVED** [review]

**Pull request merged**
