### PR TITLE
Update LocalRest to HEAD

### PR DESCRIPTION
**Pull request by Geod24**
It contains improvement for serialization which we'll need soon.

### CODE REVIEW

**Comment by Geod24** [comment]
Updated with https://github.com/Geod24/localrest/pull/65

**Comment by Geod24** [comment]
```
#### INTERNAL ERROR: Trying to access node at address 'Validator #2 (GALZ...SWTG)' without first creating it
This node was started at source/agora/test/Base.d:303
Info: :memory:
Please file a bug at https://github.com/Geod24/localrest/
core.exception.InvalidMemoryOperationError@core/exception.d(647): Invalid memory operation
Full error: core.exception.AssertError@source/agora/test/Base.d(452): Trying to access node at address 'Validator #2 (GALZ...SWTG)' without first creating it
----------------
----------------
??:? _d_assert_msg [0x10fffce86]
Program exited with code 1
/Users/runner/runners/2.169.1/work/agora/agora/source/agora/test/Base.d:452 agora.api.Validator.API agora.test.Base.TestNetworkManager.getClient(immutable(char)[], core.time.Duration) [0x10f6745e5]
/Users/runner/runners/2.169.1/work/agora/agora/source/agora/network/NetworkManager.d:379 void agora.network.NetworkManager.NetworkManager.tryConnecting(immutable(char)[], bool) [0x10f6c4db2]
/Users/runner/runners/2.169.1/work/agora/agora/source/agora/network/NetworkManager.d:514 void agora.network.NetworkManager.NetworkManager.connectNextAddresses().__lambda1() [0x10f6c6354]
/Users/runner/hostedtoolcache/dc/ldc2-1.21.0/x64/ldc2-1.21.0-osx-x86_64/bin/../import/std/regex/internal/thompson.d:902 void geod24.concurrency.FiberScheduler.create(void delegate()).wrap() [0x10fba531f]
??:? fiber_entryPoint [0x110004938]
#### INTERNAL ERROR: Trying to access node at address 'Validator #3 (GDQD...GJOM)' without first creating it
This node was started at source/agora/test/Base.d:298
Please file a bug at https://github.com/Geod24/localrest/
```

Oops, looks like another race condition here.

**Comment by AndrejMitrovic** [comment]
Well at least it's revealing hidden bugs, that's good.

**Comment by Geod24** [comment]
It's weird though. It logs both validator and full node as `Validator #XXX`, it seems (look at "This node was started at [...]").

**Comment by AndrejMitrovic** [comment]
We might want to add file+line info to `createNewNode` and pass it off to `spawn`, otherwise we can't see which module's test-case triggers the bug.

**Comment by AndrejMitrovic** [comment]
> It's weird though. It logs both validator and full node as Validator #XXX, it seems (look at "This node was started at [...]").

I just see three different Validator nodes in the logs:

```
#### INTERNAL ERROR: Trying to access node at address 'Validator #3 (GDQD...GJOM)' without first creating it
This node was started at source/agora/test/Base.d:298

#### INTERNAL ERROR: Trying to access node at address 'Validator #0 (GAJA...5RJP)' without first creating it
This node was started at source/agora/test/Base.d:298

#### INTERNAL ERROR: Trying to access node at address 'Validator #2 (GALZ...SWTG)' without first creating it
This node was started at source/agora/test/Base.d:303
```

But maybe I'm looking at the wrong log file? Which one are you looking at?

**Comment by Geod24** [comment]
https://github.com/bpfkorea/agora/pull/787/checks?check_run_id=661800372#step:8:66

**Comment by AndrejMitrovic** [comment]
Oh I see it now.

**Comment by AndrejMitrovic** [comment]
Ok I see the issue.

**Comment by AndrejMitrovic** [comment]
Let me submit a PR.

**Comment by AndrejMitrovic** [comment]
Ah have you tried rebasing?

**Comment by Geod24** [comment]
Just did: https://github.com/bpfkorea/agora/pull/787/checks?check_run_id=661835882#step:8:111

**Comment by Geod24** [comment]
Well the spurious is failure and this is green. I've rerun it a couple time without failure. What do you think @AndrejMitrovic ?

**Comment by AndrejMitrovic** [comment]
I guess we'll have to wait and see when it gets triggered again. Merge at will.

**Comment by Geod24** [comment]
I need an approval though :P

**Review by AndrejMitrovic — APPROVED** [review]

**Pull request merged**
