### PR TITLE
Small fixes in the Nominator

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
I've split this off from https://github.com/bpfkorea/agora/pull/1194

### CODE REVIEW

**Review by Geod24 — APPROVED** [review]
LGTM. Last commit is a bit over-reaching (we eventually trust the Vibe.d code that send network requests), but let's go with it anyway.

**Review by TrustHenry — APPROVED** [review]

**Comment by AndrejMitrovic** [comment]
Yeah we need to get rid of the @trusted stuff, but there is so much unsafe code everywhere else that there is no way of using it without wrapping it in @trusted..

**Comment by AndrejMitrovic** [comment]
Ah it's LocalRest.wait that is unsafe.

**Comment by AndrejMitrovic** [comment]
Well, I think we should wait for Omer's work rather than changing anything in the FiberScheduler to make it safe.

**Pull request merged**
