### PR TITLE
Make preimage revealing interval configurable

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
Required for #1071 and https://github.com/bpfkorea/agora/pull/1072.

### CODE REVIEW

**Review by linked0 — APPROVED** [review]
LGTM

**Comment by AndrejMitrovic** [comment]
The CI failure is now different. It's to do with the full node not having block height 1. I'm investigating.

**Comment by AndrejMitrovic** [comment]
> The CI failure is now different.

Well it was for 1 run. But the discovery errors remain..

**Comment by AndrejMitrovic** [comment]
Update: Found a timing issue with the EnrollmentManager tests - I've added a commit to fix it.

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
