### PR TITLE
Add documentation on how to join TestNet

### PR DESCRIPTION
**Pull request by Geod24**
This will be used by people in our company and ultimately, externally.

### CODE REVIEW

**Comment by Geod24** [comment]
Depends on https://github.com/bosagora/agora/pull/3015
Need the IBD screenshot.

**Comment by Geod24** [comment]
Should be G2G.

**Comment by Geod24** [comment]
Updated CI script

**Comment by mkykadir** [comment]
First commit message relates to a “previous” commit

**Comment by Geod24** [comment]
`s/The/A/`

**Review by mkykadir — APPROVED** [review]

**Pull request merged**
