### PR TITLE
Nominator: Nomination timer changes

### PR DESCRIPTION
**Pull request by omerfirmak**
see commit-by-commit

### CODE REVIEW

**Comment by omerfirmak** [comment]
Didnt fix our particular problem, but could be a good addition nonetheless.

**Review by Geod24 — COMMENTED** [review]
Can you explain commit 2 (the revert) ?
Also tiny type in the field name in commit 3 msg.

**Comment by omerfirmak** [comment]
> Can you explain commit 2 (the revert) ?
> Also tiny type in the field name in commit 3 msg.

We should keep nominating until atleast a single value makes it to balloting phase. If we stop nominating halfway and no Value has made it to the balloting phase, we are doomed. We should find another way to limit the number of nominations.

**Review by hewison-chris — APPROVED** [review]
LGTM

**Review by linked0 — APPROVED** [review]
LGTM

**Comment by Geod24** [comment]
Trying to get a green run, rebased on v0.x.x

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
