### PR TITLE
Update ocean to the latest HEAD + Windows fixes

### PR DESCRIPTION
**Pull request by Geod24**
This will allow us to compile on Windows, and weed out some deprecations at the same time.

### CODE REVIEW

**Review by TrustHenry — APPROVED** [review]
Looks good to windows :)

**Comment by AndrejMitrovic** [comment]
I haven't actually looked at the ocean diff yet, but I'll do it post-review since this is blocking progress.

**Comment by AndrejMitrovic** [comment]
Ocean changes look good. 👍

**Comment by Geod24** [comment]
Thanks for checking ! I was hoping to reduce the diff, but there's little that can be done if Ocean cannot depend on Phobos, and that's not happening any time soon...

**Pull request merged**
