### PR TITLE
Fix "Restart" unittest to not crash 

### PR DESCRIPTION
**Pull request by Geod24**
Pretty self-explanatory. Also added a trivial commit cleaning up a leftover copy-pasted import.

### CODE REVIEW

**Review by hewison-chris — APPROVED** [review]
LGTM

**Review by linked0 — APPROVED** [review]

**Review by kchulj — APPROVED** [review]
LGTM

**Comment by Geod24** [comment]
So, this needs more work:
1) I can still see the crash sometimes - But it's not systematic, at least, and it properly fails, e.g.
```
Unittesting agora.test.RestoreSCPState (took 4 secs, 317 ms, 927 μs, and 1 hnsec)
Unittesting agora.test.Restart================================ ASSERT HANDLER ===============================
[source/agora/test/Base.d:1270] Assertion thrown during test: Trying to access node at address 'Validator #3 (boa1xrval6hd8szdektyz69fnqjwqfejhu4rvrpwlahh9rhaazzpvs5g6lh34l5)' without first creating it
source/agora/test/Base.d:1270 agora.test.Base.TestAPI agora.test.Base.TestNetworkManager.getClient(immutable(char)[], core.time.Duration) [0x5563350b9bd2]
source/agora/network/Manager.d:167 void agora.network.Manager.NetworkManager.ConnectionTask.connect_canthrow() [0x5563351b6d7f]
source/agora/network/Manager.d:158 nothrow void agora.network.Manager.NetworkManager.ConnectionTask.connect() [0x5563351b6c9c]
core/thread/context.d:46 void core.thread.context.Callable.opCall() [0x556335c8b64c]
core/thread/fiber.d:1141 void core.thread.fiber.Fiber.run() [0x556335c2cd18]
core/thread/fiber.d:198 fiber_entryPoint [0x556335c2cc55]
./ci/run.sh: line 21:  4680 Aborted                 (core dumped) ./build/agora-unittests
+ ./build/agora-unittests
Unittesting scpd.types.Stellar_types (took 3 hnsecs)
```

2) In the past I've seen another error being triggered, but it went away, so I'm starting to think it's unrelated. Will investigate.

**Comment by Geod24** [comment]
> I can still see the crash sometimes - But it's not systematic, at least, and it properly fails, e.g.

Okay, the issue was actually simple: We need to wait for restart to be completed before shutting things down. Otherwise, the network might already be torn down by the time the network tries to connect, hence the assert.

**Pull request merged**
