### PR TITLE
[CI] Test compiler HEAD versions on branch push only

### PR DESCRIPTION
**Pull request by AndrejMitrovic**

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
I've asked for help in https://github.community/t5/GitHub-Actions/Github-Actions-unresponsive-while-splitting-on-push-PR-action/m-p/43895#M5550

**Review by weide-zhou — APPROVED** [review]

**Comment by AndrejMitrovic** [comment]
Unfortunately we cannot avoid the duplication. And the PR/push has to be split into two files according to https://github.community/t5/GitHub-Actions/Github-Actions-unresponsive-while-splitting-on-push-PR-action/m-p/43912/highlight/true#M5560.

PR updated.

**Comment by AndrejMitrovic** [comment]
I've submitted a support ticket to docker. In the meantime I'm marking this as blocked again.

**Comment by AndrejMitrovic** [comment]
@Geod24 this could be merged if you just ignore the docker cloud failure. I still don't know why it fails, but I opened a support ticket.

**Comment by AndrejMitrovic** [comment]
Ah by the way, if `v0.x.x` fails, will you get notifications? Might want to turn those off..

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
