### PR TITLE
Re-enable all tests

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
The commit 27793a0ff837baecb6b5a78579d902ae5ff7fc4a
accidentally disabled most tests.

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
I'll fix the test failure too, it was hidden.

**Comment by AndrejMitrovic** [comment]
Alright the test-suite failure is minimal, it's because the stakes changed in https://github.com/bpfkorea/agora/pull/1086/commits/882bb3b0b56141cf37f91f069fd9caf03a3a0dda and therefore the quorum sets have changed slightly. I'll fix up the QuorumPreimage tests.

**Comment by AndrejMitrovic** [comment]
Added fixup. I'll merge this if it goes green.

**Comment by Geod24** [comment]
Well done :P

**Pull request merged**
