### PR TITLE
Optimize checkNominate() run time

### PR DESCRIPTION
**Pull request by omerfirmak**
`checkNominate()` tends to overrun it's period and hog all the CPU cycles. I am hoping these to help, along with https://github.com/bosagora/vibe-core/pull/1

### CODE REVIEW

**Comment by omerfirmak** [comment]
these bring checkNominate runtine from 8-10secs to 90ms

**Review by Geod24 — APPROVED** [review]
LGTM

**Comment by Geod24** [comment]
But not to the CI:
```
Unittesting agora.consensus.Ledger================================ ASSERT HANDLER ===============================
[source/agora/consensus/Ledger.d:1566] Assertion thrown during test: "" != "Higher bound violation - Missing validator mismatch [2, 5] is not a subset of [2]"
source/agora/consensus/Ledger.d:1566 void agora.consensus.Ledger.__unittest_L1535_C1() [0x102ff9b6d]
source/agora/consensus/Ledger.d agora.consensus.Ledger.__unittest [0x103832afd]
source/agora/test/Base.d:300 bool agora.test.Base.customModuleUnitTester().runTest(agora.test.Base.customModuleUnitTester().ModTest) [0x103558294]
source/agora/test/Base.d:327 bool agora.test.Base.customModuleUnitTester().runSerially(agora.test.Base.customModuleUnitTester().ModTest[]) [0x1035586e5]
source/agora/test/Base.d:372 core.runtime.UnitTestResult agora.test.Base.customModuleUnitTester() [0x1032df356]
core/runtime.d:580 runModuleUnitTests [0x10437d370]
rt/dmain2.d:487 void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x104396392]
rt/dmain2.d:461 void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x104396302]
rt/dmain2.d:520 _d_run_main2 [0x1043961b9]
rt/dmain2.d:320 _d_run_main [0x104395e80]
/Users/runner/hostedtoolcache/dc/ldc2-1.28.1/x64/ldc2-1.28.1-osx-x86_64/bin/../import/core/internal/entrypoint.d:42 main [0x103562f41]
2022-01-28 13:00:04,108 Info [agora.consensus.state.Ledger] - Last known block: #0 
```

**Comment by omerfirmak** [comment]
Well, I didnt hash `initial_missing_validators` since the missing validator list can only get smaller for the same slot, not bigger. So a valid value will always be valid, even if `initial_missing_validators` changes. Will change the tests.

**Comment by omerfirmak** [comment]
Fixed the test

**Pull request merged**
