### PR TITLE
Update LocalRest for add setTimer function

### PR DESCRIPTION
**Pull request by TrustHenry**
See LocalRest PR https://github.com/Geod24/localrest/pull/69

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
@TrustHenry how about using it?

https://github.com/bpfkorea/agora/blob/bebe6555052b830bff1040847edd035046d24cd4/source/agora/consensus/protocol/Nominator.d#L507-L509

https://github.com/bpfkorea/agora/blob/bebe6555052b830bff1040847edd035046d24cd4/source/agora/network/NetworkManager.d#L203-L210

https://github.com/bpfkorea/agora/blob/bebe6555052b830bff1040847edd035046d24cd4/source/agora/network/NetworkManager.d#L235-L246

**Comment by TrustHenry** [comment]
I think can change it to that function. 
But I think it would be good to change it to a separate PR from the update PR.

**Comment by AndrejMitrovic** [comment]
Sure.

**Review by AndrejMitrovic — APPROVED** [review]

**Comment by AndrejMitrovic** [comment]
Only the build artifacts failed, so I will merge as-is.

**Comment by AndrejMitrovic** [comment]
Ah CircleCI failed too. Let me re-run it.

**Pull request merged**
