### PR TITLE
Use alpine:edge for the runner image

### PR DESCRIPTION
**Pull request by Geod24**
Let's see if this works as expected.

### CODE REVIEW

**Review by kchulj — APPROVED** [review]

**Comment by Geod24** [comment]
This is blocked by:
- An update to dtools which currently doesn't work;
- Which in turns is blocked by LDC segfaulting when an exception is thrown;
- Which is fixed by backporting my libunwind patches to LDC v1.25.0
- Which is blocked by LDC v1.25.0 existing (I could backport to v1.24.0 but it'll be much more work);
- LDC v1.25.0 **should** be released in around a month at most, according to the usual schedule;

**Comment by Geod24** [comment]
Should be unblocked. I regenerated `agora-builder` already. We don't yet have the `dub` upgrade, because of some regression, but we don't need it for LDC v1.25.0. Worst case scenario we can just compile our own.

**Comment by Geod24** [comment]
💚

**Comment by AndrejMitrovic** [comment]
I still see 4 runs in progress?

**Review by AndrejMitrovic — APPROVED** [review]

**Comment by Geod24** [comment]
> I still see 4 runs in progress?

This PR only affects CircleCI (the only user of the docker image)

**Comment by AndrejMitrovic** [comment]
Doh that's a good point. I'll merge it.

**Pull request merged**
