### PR TITLE
CI: Run under gdb

### PR DESCRIPTION
**Pull request by omerfirmak**
Lets see if gdb can tell us something useful about the failures

### CODE REVIEW

**Comment by omerfirmak** [comment]
It seems like we are running out of memory :(

**Review by kchulj — APPROVED** [review]

**Comment by AndrejMitrovic** [comment]
> It seems like we are running out of memory :(

How do you figure that?

**Comment by Geod24** [comment]
Here's what `ldc-1.24` is showing:
```
Thread 394 "agora-unittests" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffd2e675700 (LWP 8284)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff5979921 in __GI_abort () at abort.c:79
#2  0x00005555560b4d0c in core.thread.fiber.Fiber.allocStack(ulong, ulong) (this=0x7ffd4c7b1780, sz=528384, guardPageSize=4096) at fiber.d:1283
#3  0x00005555560b4d90 in _D4core6thread5fiber5Fiber6__ctorMFNbDFZvmmZCQBrQBpQBlQBi (this=0x7ffd4c7b1780, dg=..., sz=524288, guardPageSize=4096) at fiber.d:817
#4  0x0000555555ec050f in _D6geod2411concurrency14FiberScheduler9InfoFiber6__ctorMFNbDFZvmZCQCmQCiQByQBl (this=0x7ffd4c7b1780, op=..., sz=524288) at concurrency.d:933
#5  0x0000555555ebffa3 in geod24.concurrency.FiberScheduler.create(void() delegate) (this=0x7fff5bf03660, op=...) at concurrency.d:918
#6  0x0000555555ec0314 in geod24.concurrency.FiberScheduler.spawn(void() delegate) (this=0x7fff5bf03660, op=...) at concurrency.d:843
#7  0x000055555584aedc in _D6geod249LocalRest__T9RemoteAPITC5agora4test4Base7TestAPITSQBaQxQu10SerializerZQCg__T7spawnedTCQCkQChQCf17TestValidatorNodeZQBnFNbSQFa11concurrency3TidAyaiSQEt6common6ConfigQhPOSQGv8RegistryQjAySQGg9consensus4data5BlockQgISQHiQHfQHd8TestConfPOmZ7runNodeMFZ__T6handleTSQKhQKd7CommandZQyMFNbQwZv (arg=...) at /home/runner/work/agora/agora/submodules/localrest/source/geod24/LocalRest.d:602
```

(Removed a lot of `warning: (Internal error: pc 0x5555560b4d0b in read in psymtab, but not in symtab.)` for readability).
The `abort` is raised on L1283, which is [here](https://github.com/ldc-developers/druntime/blob/ldc-v1.24.0/src/core/thread/fiber.d#L1283). So `mprotect` fails.

**Comment by Geod24** [comment]
I wonder if druntime shouldn't be using the proper flags (`MAP_GROWSDOWN`) here...

**Comment by omerfirmak** [comment]
We are hitting [this](https://github.com/bpfkorea/agora/pull/1299#issuecomment-719556386) again then. Should we just apply the `vm.max_map_count` workaround?

**Comment by AndrejMitrovic** [comment]
Merging those localrest changes will also fix the issue, right?

**Comment by omerfirmak** [comment]
Yes, [this](https://github.com/Geod24/localrest/pull/103) should help

**Comment by AndrejMitrovic** [comment]
> We are hitting this again then. Should we just apply the vm.max_map_count workaround?

It's worth a shot. We can revert it once the LocalRest changes get merged.

**Comment by omerfirmak** [comment]
Ok, rerunning with a higher `vm.max_map_count`

**Pull request closed without merging**
