### PR TITLE
Add agora-history-push to allow for Stoa development

### PR DESCRIPTION
**Pull request by Geod24**
@MichaelKim20 @TrustHenry Let me know when you start to use it so I can make sure it does everything you need.

### CODE REVIEW

**Comment by Geod24** [comment]
TODO: Check compilation in the CI

**Comment by TrustHenry** [comment]
It's simple and very good.
It is pushed to JSON by reading from the ledger.

In order to find the address of Validators among the APIs that Stoa will develop first, we need to read BlockHeader's enrollments in the ledger and match the utxo_key of the enrollment with the transaction output.
In this process, transaction hashes are not stored in the ledger.
The transaction hash and the utxo_key contain index.

**Comment by AndrejMitrovic** [comment]
I'm not sure how this is supposed to be used? It's going to read the blockchain from the same drive as a currently running node? What if the node is writing to the blockstorage on disk while this app is reading from it?

**Comment by Geod24** [comment]
> I'm not sure how this is supposed to be used? It's going to read the blockchain from the same drive as a currently running node? What if the node is writing to the blockstorage on disk while this app is reading from it?

Yes it's a utility tool for the moment, so better run it with a storage that is shut down or blocks that have already been written. Although ideally we should update the storage atomically. Hence why I left it as a WIP, it is solely there for @MichaelKim20 and @TrustHenry to test.

**Comment by AndrejMitrovic** [comment]
Oh it's just a utility, I get it.

**Review by AndrejMitrovic — APPROVED** [review]

**Comment by TrustHenry** [comment]
@Geod24 'd better define the key in POST and send the data in the value.

**Comment by TrustHenry** [comment]
^ It works well.

**Comment by TrustHenry** [comment]
I think we need to logically process the HTTP response code.
200: OK
400: Not a valid JSON format, Missing 'block' object in body
500: An error occurred while saving

**Review by MichaelKim20 — APPROVED** [review]
LGTM

**Comment by Geod24** [comment]
I'll rebased and git it green soon

**Comment by TrustHenry** [comment]
@Geod24 Are you thinking of a trigger or event to run this periodically later?

**Comment by Geod24** [comment]
With the current state of Stoa, and the new features in Agora, I don't think we need this anymore. Closing.

**Pull request closed without merging**
